package com.grandfatherpikhto.blin

import android.os.ParcelUuid
import java.util.*

object GenericUUIDs {
    /**
     * List from https://btprodspecificationrefs.blob.core.windows.net/assigned-values/16-bit%20UUID%20Numbers%20Document.pdf
     * The 16-bit UUID Numbers Document contains the following value types:
     * GATT Service,
     * GATT Unit,
     * GATT Declaration,
     * GATT Descriptor,
     * GATT Characteristic
     * and
     * Object Type,
     * 16-bit UUID for members,
     * Protocol Identifier,
     *.SDOGattService GATT Service,
     * Service Class and Profile.
     */
    const val TAG:String = "GenericUUIDs"

    data class UUID16(val type: Type, val uuid:Int, val name:String? = null) {
        constructor(uuid: UUID, type: Type = Type.All) : this(type, uuid.to16())
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (javaClass != other?.javaClass) return false

            other as UUID16

            if (type != other.type) return false
            if (uuid != other.uuid) return false

            return true
        }

        override fun hashCode(): Int {
            var result = type.hashCode()
            result = 31 * result + uuid
            return result
        }
    }

    fun UUID.genericName(type: Type = Type.All) : String? = findGeneric(type)?.name

    fun UUID.genericStringUUID(type:Type = Type.All) : String {
        val generic = findGeneric(type)
        if (generic != null) {
            return String.format("%04X", generic.uuid)
        }

        return toString().uppercase()
    }


    /**
     * Проверяет, является ли UUID -- Основным (generic)
     */
    fun UUID.isGeneric():Boolean {
        return this.mostSignificantBits and -0xffff00000001L == 0x1000L
    }

    fun UUID.findGeneric(type: Type = Type.All) : UUID16? {
        if (isGeneric()) {
            if (type != Type.All) {
                return genericUuids.find { it.uuid == to16()
                        && it.type == type }
            }
            return genericUuids.find { it.uuid == to16() }
        }
        return null
    }

    /**
     * Выделить 16-битный идентификатор из generic UUID
     */
    fun ParcelUuid.to16():Int {
        return this.uuid.to16()
    }

    /**
     * Возвращает 16-битное представление generic UUID
     */
    fun UUID.to16():Int {
        return this.mostSignificantBits.shr(32).and(0xFFFF).toInt()
    }

    /**
     * Проверяет, является ли ParcelUUID -- Основным (Generic)
     */
    fun ParcelUuid.isGeneric():Boolean {
        return this.uuid.isGeneric()
    }


    enum class Type(val value:Int) {
        All(0x00),
        Member(0x01),
        Characteristic(0x02),
        Descriptor(0x03),
        Unit(0x04),
        SDOGattService(0x05),
        Protocol(0x06),
        ClassAndProfile(0x07),
        Service(0x08),
        Declaration(0x09),
        None(0xFF)
    }

    val genericUuids = arrayOf<UUID16>(
        UUID16(	Type.Member, 0xFD00, "FUTEK Advanced Sensor Technology, Inc."),
        UUID16(	Type.Member, 0xFD01, "Sanvita Medical Corporation"),
        UUID16(	Type.Member, 0xFD02, "LEGO System A/S"),
        UUID16(	Type.Member, 0xFD03, "Quuppa Oy"),
        UUID16(	Type.Member, 0xFD04, "Shure Inc."),
        UUID16(	Type.Member, 0xFD05, "Qualcomm Technologies, Inc."),
        UUID16(	Type.Member, 0xFD06, "RACE-AI LLC"),
        UUID16(	Type.Member, 0xFD07, "Swedlock AB"),
        UUID16(	Type.Member, 0xFD08, "Bull Group Incorporated Company"),
        UUID16(	Type.Member, 0xFD09, "Cousins and Sears LLC"),
        UUID16(	Type.Member, 0xFD0A, "Luminostics, Inc."),
        UUID16(	Type.Member, 0xFD0B, "Luminostics, Inc."),
        UUID16(	Type.Member, 0xFD0C, "OSM HK Limited"),
        UUID16(	Type.Member, 0xFD0D, "Blecon Ltd"),
        UUID16(	Type.Member, 0xFD0E, "HerdDogg, Inc"),
        UUID16(	Type.Member, 0xFD0F, "AEON MOTOR CO.,LTD."),
        UUID16(	Type.Member, 0xFD10, "AEON MOTOR CO.,LTD."),
        UUID16(	Type.Member, 0xFD11, "AEON MOTOR CO.,LTD."),
        UUID16(	Type.Member, 0xFD12, "AEON MOTOR CO.,LTD."),
        UUID16(	Type.Member, 0xFD13, "BRG Sports, Inc."),
        UUID16(	Type.Member, 0xFD14, "BRG Sports, Inc."),
        UUID16(	Type.Member, 0xFD15, "Panasonic Corporation"),
        UUID16(	Type.Member, 0xFD16, "Sensitech, Inc."),
        UUID16(	Type.Member, 0xFD17, "LEGIC Identsystems AG"),
        UUID16(	Type.Member, 0xFD18, "LEGIC Identsystems AG"),
        UUID16(	Type.Member, 0xFD19, "Smith & Nephew Medical Limited"),
        UUID16(	Type.Member, 0xFD1A, "CSIRO"),
        UUID16(	Type.Member, 0xFD1B, "Helios Sports, Inc."),
        UUID16(	Type.Member, 0xFD1C, "Brady Worldwide Inc."),
        UUID16(	Type.Member, 0xFD1D, "Samsung Electronics Co., Ltd"),
        UUID16(	Type.Member, 0xFD1E, "Plume Design Inc."),
        UUID16(	Type.Member, 0xFD1F, "3M"),
        UUID16(	Type.Member, 0xFD20, "GN Hearing A/S"),
        UUID16(	Type.Member, 0xFD21, "Huawei Technologies Co., Ltd."),
        UUID16(	Type.Member, 0xFD22, "Huawei Technologies Co., Ltd."),
        UUID16(	Type.Member, 0xFD23, "DOM Sicherheitstechnik GmbH & Co. KG"),
        UUID16(	Type.Member, 0xFD24, "GD Midea Air-Conditioning Equipment Co., Ltd."),
        UUID16(	Type.Member, 0xFD25, "GD Midea Air-Conditioning Equipment Co., Ltd."),
        UUID16(	Type.Member, 0xFD26, "Novo Nordisk A/S"),
        UUID16(	Type.Member, 0xFD27, "i2Systems"),
        UUID16(	Type.Member, 0xFD28, "Julius Blum GmbH"),
        UUID16(	Type.Member, 0xFD29, "Asahi Kasei Corporation"),
        UUID16(	Type.Member, 0xFD2A, "Sony Corporation"),
        UUID16(	Type.Member, 0xFD2B, "The Access Technologies"),
        UUID16(	Type.Member, 0xFD2C, "The Access Technologies"),
        UUID16(	Type.Member, 0xFD2D, "Xiaomi Inc."),
        UUID16(	Type.Member, 0xFD2E, "Bitstrata Systems Inc."),
        UUID16(	Type.Member, 0xFD2F, "Bitstrata Systems Inc."),
        UUID16(	Type.Member, 0xFD30, "Sesam Solutions BV"),
        UUID16(	Type.Member, 0xFD31, "LG Electronics Inc."),
        UUID16(	Type.Member, 0xFD32, "Gemalto Holding BV"),
        UUID16(	Type.Member, 0xFD33, "DashLogic, Inc."),
        UUID16(	Type.Member, 0xFD34, "Aerosens LLC."),
        UUID16(	Type.Member, 0xFD35, "Transsion Holdings Limited"),
        UUID16(	Type.Member, 0xFD36, "Google LLC"),
        UUID16(	Type.Member, 0xFD37, "TireCheck GmbH"),
        UUID16(	Type.Member, 0xFD38, "Danfoss A/S"),
        UUID16(	Type.Member, 0xFD39, "PREDIKTAS"),
        UUID16(	Type.Member, 0xFD3A, "Verkada Inc."),
        UUID16(	Type.Member, 0xFD3B, "Verkada Inc."),
        UUID16(	Type.Member, 0xFD3C, "Redline Communications Inc."),
        UUID16(	Type.Member, 0xFD3D, "Woan Technology (Shenzhen) Co., Ltd."),
        UUID16(	Type.Member, 0xFD3E, "Pure Watercraft, inc."),
        UUID16(	Type.Member, 0xFD3F, "Cognosos, Inc"),
        UUID16(	Type.Member, 0xFD40, "Beflex Inc."),
        UUID16(	Type.Member, 0xFD41, "Amazon Lab126"),
        UUID16(	Type.Member, 0xFD42, "Globe (Jiangsu) Co.,Ltd"),
        UUID16(	Type.Member, 0xFD43, "Apple Inc."),
        UUID16(	Type.Member, 0xFD44, "Apple Inc."),
        UUID16(	Type.Member, 0xFD45, "GB Solution co.,Ltd"),
        UUID16(	Type.Member, 0xFD46, "Lemco IKE"),
        UUID16(	Type.Member, 0xFD47, "Liberty Global Inc."),
        UUID16(	Type.Member, 0xFD48, "Geberit International AG"),
        UUID16(	Type.Member, 0xFD49, "Panasonic Corporation"),
        UUID16(	Type.Member, 0xFD4A, "Sigma Elektro GmbH"),
        UUID16(	Type.Member, 0xFD4B, "Samsung Electronics Co., Ltd."),
        UUID16(	Type.Member, 0xFD4C, "Adolf Wuerth GmbH & Co KG"),
        UUID16(	Type.Member, 0xFD4D, "70mai Co.,Ltd."),
        UUID16(	Type.Member, 0xFD4E, "70mai Co.,Ltd."),
        UUID16(	Type.Member, 0xFD4F, "Forkbeard Technologies AS"),
        UUID16(	Type.Member, 0xFD50, "Hangzhou Tuya Information Technology Co., Ltd"),
        UUID16(	Type.Member, 0xFD51, "UTC Fire and Security"),
        UUID16(	Type.Member, 0xFD52, "UTC Fire and Security"),
        UUID16(	Type.Member, 0xFD53, "PCI Private Limited"),
        UUID16(	Type.Member, 0xFD54, "Qingdao Haier Technology Co., Ltd."),
        UUID16(	Type.Member, 0xFD55, "Braveheart Wireless, Inc."),
        UUID16(	Type.Member, 0xFD56, "Resmed Ltd"),
        UUID16(	Type.Member, 0xFD57, "Volvo Car Corporation"),
        UUID16(	Type.Member, 0xFD58, "Volvo Car Corporation"),
        UUID16(	Type.Member, 0xFD59, "Samsung Electronics Co., Ltd."),
        UUID16(	Type.Member, 0xFD5A, "Samsung Electronics Co., Ltd."),
        UUID16(	Type.Member, 0xFD5B, "V2SOFT INC."),
        UUID16(	Type.Member, 0xFD5C, "React Mobile"),
        UUID16(	Type.Member, 0xFD5D, "maxon motor ltd."),
        UUID16(	Type.Member, 0xFD5E, "Tapkey GmbH"),
        UUID16(	Type.Member, 0xFD5F, "Oculus VR, LLC"),
        UUID16(	Type.Member, 0xFD60, "Sercomm Corporation"),
        UUID16(	Type.Member, 0xFD61, "Arendi AG"),
        UUID16(	Type.Member, 0xFD62, "Fitbit, Inc."),
        UUID16(	Type.Member, 0xFD63, "Fitbit, Inc."),
        UUID16(	Type.Member, 0xFD64, "INRIA"),
        UUID16(	Type.Member, 0xFD65, "Razer Inc."),
        UUID16(	Type.Member, 0xFD66, "Zebra Technologies Corporation"),
        UUID16(	Type.Member, 0xFD67, "Montblanc Simplo GmbH"),
        UUID16(	Type.Member, 0xFD68, "Ubique Innovation AG"),
        UUID16(	Type.Member, 0xFD69, "Samsung Electronics Co., Ltd"),
        UUID16(	Type.Member, 0xFD6A, "Emerson"),
        UUID16(	Type.Member, 0xFD6B, "rapitag GmbH"),
        UUID16(	Type.Member, 0xFD6C, "Samsung Electronics Co., Ltd."),
        UUID16(	Type.Member, 0xFD6D, "Sigma Elektro GmbH"),
        UUID16(	Type.Member, 0xFD6E, "Polidea sp. z o.o."),
        UUID16(	Type.Member, 0xFD6F, "Apple, Inc."),
        UUID16(	Type.Member, 0xFD70, "GuangDong Oppo Mobile Telecommunications Corp., Ltd"),
        UUID16(	Type.Member, 0xFD71, "GN Hearing A/S"),
        UUID16(	Type.Member, 0xFD72, "Logitech International SA"),
        UUID16(	Type.Member, 0xFD73, "BRControls Products BV"),
        UUID16(	Type.Member, 0xFD74, "BRControls Products BV"),
        UUID16(	Type.Member, 0xFD75, "Insulet Corporation"),
        UUID16(	Type.Member, 0xFD76, "Insulet Corporation"),
        UUID16(	Type.Member, 0xFD77, "Withings"),
        UUID16(	Type.Member, 0xFD78, "Withings"),
        UUID16(	Type.Member, 0xFD79, "Withings"),
        UUID16(	Type.Member, 0xFD7A, "Withings"),
        UUID16(	Type.Member, 0xFD7B, "WYZE LABS, INC."),
        UUID16(	Type.Member, 0xFD7C, "Toshiba Information Systems(Japan) Corporation"),
        UUID16(	Type.Member, 0xFD7D, "Center for Advanced Research Wernher Von Braun"),
        UUID16(	Type.Member, 0xFD7E, "Samsung Electronics Co., Ltd."),
        UUID16(	Type.Member, 0xFD7F, "Husqvarna AB"),
        UUID16(	Type.Member, 0xFD80, "Phindex Technologies, Inc"),
        UUID16(	Type.Member, 0xFD81, "CANDY HOUSE, Inc."),
        UUID16(	Type.Member, 0xFD82, "Sony Corporation"),
        UUID16(	Type.Member, 0xFD83, "iNFORM Technology GmbH"),
        UUID16(	Type.Member, 0xFD84, "Tile, Inc."),
        UUID16(	Type.Member, 0xFD85, "Husqvarna AB"),
        UUID16(	Type.Member, 0xFD86, "Abbott"),
        UUID16(	Type.Member, 0xFD87, "Google LLC"),
        UUID16(	Type.Member, 0xFD88, "Urbanminded LTD"),
        UUID16(	Type.Member, 0xFD89, "Urbanminded LTD"),
        UUID16(	Type.Member, 0xFD8A, "Signify Netherlands B.V."),
        UUID16(	Type.Member, 0xFD8B, "Jigowatts Inc."),
        UUID16(	Type.Member, 0xFD8C, "Google LLC"),
        UUID16(	Type.Member, 0xFD8D, "quip NYC Inc."),
        UUID16(	Type.Member, 0xFD8E, "Motorola Solutions"),
        UUID16(	Type.Member, 0xFD8F, "Matrix ComSec Pvt. Ltd."),
        UUID16(	Type.Member, 0xFD90, "Guangzhou SuperSound Information Technology Co.,Ltd"),
        UUID16(	Type.Member, 0xFD91, "Groove X, Inc."),
        UUID16(	Type.Member, 0xFD92, "Qualcomm Technologies International, Ltd. (QTIL)"),
        UUID16(	Type.Member, 0xFD93, "Bayerische Motoren Werke AG"),
        UUID16(	Type.Member, 0xFD94, "Hewlett Packard Enterprise"),
        UUID16(	Type.Member, 0xFD95, "Rigado"),
        UUID16(	Type.Member, 0xFD96, "Google LLC"),
        UUID16(	Type.Member, 0xFD97, "June Life, Inc."),
        UUID16(	Type.Member, 0xFD98, "Disney Worldwide Services, Inc."),
        UUID16(	Type.Member, 0xFD99, "ABB Oy"),
        UUID16(	Type.Member, 0xFD9A, "Huawei Technologies Co., Ltd."),
        UUID16(	Type.Member, 0xFD9B, "Huawei Technologies Co., Ltd."),
        UUID16(	Type.Member, 0xFD9C, "Huawei Technologies Co., Ltd."),
        UUID16(	Type.Member, 0xFD9D, "Gastec Corporation"),
        UUID16(	Type.Member, 0xFD9E, "The Coca-Cola Company"),
        UUID16(	Type.Member, 0xFD9F, "VitalTech Affiliates LLC"),
        UUID16(	Type.Member, 0xFDA0, "Secugen Corporation"),
        UUID16(	Type.Member, 0xFDA1, "Groove X, Inc"),
        UUID16(	Type.Member, 0xFDA2, "Groove X, Inc"),
        UUID16(	Type.Member, 0xFDA3, "Inseego Corp."),
        UUID16(	Type.Member, 0xFDA4, "Inseego Corp."),
        UUID16(	Type.Member, 0xFDA5, "Neurostim OAB, Inc."),
        UUID16(	Type.Member, 0xFDA6, "WWZN Information Technology Company Limited"),
        UUID16(	Type.Member, 0xFDA7, "WWZN Information Technology Company Limited"),
        UUID16(	Type.Member, 0xFDA8, "PSA Peugeot Citroën"),
        UUID16(	Type.Member, 0xFDA9, "Rhombus Systems, Inc."),
        UUID16(	Type.Member, 0xFDAA, "Xiaomi Inc."),
        UUID16(	Type.Member, 0xFDAB, "Xiaomi Inc."),
        UUID16(	Type.Member, 0xFDAC, "Tentacle Sync GmbH"),
        UUID16(	Type.Member, 0xFDAD, "Houwa System Design, k.k."),
        UUID16(	Type.Member, 0xFDAE, "Houwa System Design, k.k."),
        UUID16(	Type.Member, 0xFDAF, "Wiliot LTD"),
        UUID16(	Type.Member, 0xFDB0, "Proxy Technologies, Inc."),
        UUID16(	Type.Member, 0xFDB1, "Proxy Technologies, Inc."),
        UUID16(	Type.Member, 0xFDB2, "Portable Multimedia Ltd"),
        UUID16(	Type.Member, 0xFDB3, "Audiodo AB"),
        UUID16(	Type.Member, 0xFDB4, "HP Inc"),
        UUID16(	Type.Member, 0xFDB5, "ECSG"),
        UUID16(	Type.Member, 0xFDB6, "GWA Hygiene GmbH"),
        UUID16(	Type.Member, 0xFDB7, "LivaNova USA Inc."),
        UUID16(	Type.Member, 0xFDB8, "LivaNova USA Inc."),
        UUID16(	Type.Member, 0xFDB9, "Comcast Cable Corporation"),
        UUID16(	Type.Member, 0xFDBA, "Comcast Cable Corporation"),
        UUID16(	Type.Member, 0xFDBB, "Profoto"),
        UUID16(	Type.Member, 0xFDBC, "Emerson"),
        UUID16(	Type.Member, 0xFDBD, "Clover Network, Inc."),
        UUID16(	Type.Member, 0xFDBE, "California Things Inc."),
        UUID16(	Type.Member, 0xFDBF, "California Things Inc."),
        UUID16(	Type.Member, 0xFDC0, "Hunter Douglas"),
        UUID16(	Type.Member, 0xFDC1, "Hunter Douglas"),
        UUID16(	Type.Member, 0xFDC2, "Baidu Online Network Technology (Beijing) Co., Ltd"),
        UUID16(	Type.Member, 0xFDC3, "Baidu Online Network Technology (Beijing) Co., Ltd"),
        UUID16(	Type.Member, 0xFDC4, "Simavita (Aust) Pty Ltd"),
        UUID16(	Type.Member, 0xFDC5, "Automatic Labs"),
        UUID16(	Type.Member, 0xFDC6, "Eli Lilly and Company"),
        UUID16(	Type.Member, 0xFDC7, "Eli Lilly and Company"),
        UUID16(	Type.Member, 0xFDC8, "Hach – Danaher"),
        UUID16(	Type.Member, 0xFDC9, "Busch-Jaeger Elektro GmbH"),
        UUID16(	Type.Member, 0xFDCA, "Fortin Electronic Systems"),
        UUID16(	Type.Member, 0xFDCB, "Meggitt SA"),
        UUID16(	Type.Member, 0xFDCC, "Shoof Technologies"),
        UUID16(	Type.Member, 0xFDCD, "Qingping Technology (Beijing) Co., Ltd."),
        UUID16(	Type.Member, 0xFDCE, "SENNHEISER electronic GmbH & Co. KG"),
        UUID16(	Type.Member, 0xFDCF, "Nalu Medical, Inc"),
        UUID16(	Type.Member, 0xFDD0, "Huawei Technologies Co., Ltd"),
        UUID16(	Type.Member, 0xFDD1, "Huawei Technologies Co., Ltd"),
        UUID16(	Type.Member, 0xFDD2, "Bose Corporation"),
        UUID16(	Type.Member, 0xFDD3, "FUBA Automotive Electronics GmbH"),
        UUID16(	Type.Member, 0xFDD4, "LX Solutions Pty Limited"),
        UUID16(	Type.Member, 0xFDD5, "Brompton Bicycle Ltd"),
        UUID16(	Type.Member, 0xFDD6, "Ministry of Supply"),
        UUID16(	Type.Member, 0xFDD7, "Emerson"),
        UUID16(	Type.Member, 0xFDD8, "Jiangsu Teranovo Tech Co., Ltd."),
        UUID16(	Type.Member, 0xFDD9, "Jiangsu Teranovo Tech Co., Ltd."),
        UUID16(	Type.Member, 0xFDDA, "MHCS"),
        UUID16(	Type.Member, 0xFDDB, "Samsung Electronics Co., Ltd."),
        UUID16(	Type.Member, 0xFDDC, "4iiii Innovations Inc."),
        UUID16(	Type.Member, 0xFDDD, "Arch Systems Inc"),
        UUID16(	Type.Member, 0xFDDE, "Noodle Technology Inc."),
        UUID16(	Type.Member, 0xFDDF, "Harman International"),
        UUID16(	Type.Member, 0xFDE0, "John Deere"),
        UUID16(	Type.Member, 0xFDE1, "Fortin Electronic Systems"),
        UUID16(	Type.Member, 0xFDE2, "Google Inc."),
        UUID16(	Type.Member, 0xFDE3, "Abbott Diabetes Care"),
        UUID16(	Type.Member, 0xFDE4, "JUUL Labs, Inc."),
        UUID16(	Type.Member, 0xFDE5, "SMK Corporation"),
        UUID16(	Type.Member, 0xFDE6, "Intelletto Technologies Inc"),
        UUID16(	Type.Member, 0xFDE7, "SECOM Co., LTD"),
        UUID16(	Type.Member, 0xFDE8, "Robert Bosch GmbH"),
        UUID16(	Type.Member, 0xFDE9, "Spacesaver Corporation"),
        UUID16(	Type.Member, 0xFDEA, "SeeScan, Inc"),
        UUID16(	Type.Member, 0xFDEB, "Syntronix Corporation"),
        UUID16(	Type.Member, 0xFDEC, "Mannkind Corporation"),
        UUID16(	Type.Member, 0xFDED, "Pole Star"),
        UUID16(	Type.Member, 0xFDEE, "Huawei Technologies Co., Ltd."),
        UUID16(	Type.Member, 0xFDEF, "ART AND PROGRAM, INC."),
        UUID16(	Type.Member, 0xFDF0, "Google Inc."),
        UUID16(	Type.Member, 0xFDF1, "LAMPLIGHT Co.,Ltd"),
        UUID16(	Type.Member, 0xFDF2, "AMICCOM Electronics Corporation"),
        UUID16(	Type.Member, 0xFDF3, "Amersports"),
        UUID16(	Type.Member, 0xFDF4, "O. E. M. Controls, Inc."),
        UUID16(	Type.Member, 0xFDF5, "Milwaukee Electric Tools"),
        UUID16(	Type.Member, 0xFDF6, "AIAIAI ApS"),
        UUID16(	Type.Member, 0xFDF7, "HP Inc."),
        UUID16(	Type.Member, 0xFDF8, "Onvocal"),
        UUID16(	Type.Member, 0xFDF9, "INIA"),
        UUID16(	Type.Member, 0xFDFA, "Tandem Diabetes Care"),
        UUID16(	Type.Member, 0xFDFB, "Tandem Diabetes Care"),
        UUID16(	Type.Member, 0xFDFC, "Optrel AG"),
        UUID16(	Type.Member, 0xFDFD, "RecursiveSoft Inc."),
        UUID16(	Type.Member, 0xFDFE, "ADHERIUM(NZ) LIMITED"),
        UUID16(	Type.Member, 0xFDFF, "OSRAM GmbH"),
        UUID16(	Type.Member, 0xFE00, "Amazon.com Services, Inc."),
        UUID16(	Type.Member, 0xFE01, "Duracell U.S. Operations Inc."),
        UUID16(	Type.Member, 0xFE02, "Robert Bosch GmbH"),
        UUID16(	Type.Member, 0xFE03, "Amazon.com Services, Inc."),
        UUID16(	Type.Member, 0xFE04, "OpenPath Security Inc"),
        UUID16(	Type.Member, 0xFE05, "CORE Transport Technologies NZ Limited"),
        UUID16(	Type.Member, 0xFE06, "Qualcomm Technologies, Inc."),
        UUID16(	Type.Member, 0xFE07, "Sonos, Inc."),
        UUID16(	Type.Member, 0xFE08, "Microsoft"),
        UUID16(	Type.Member, 0xFE09, "Pillsy, Inc."),
        UUID16(	Type.Member, 0xFE0A, "ruwido austria gmbh"),
        UUID16(	Type.Member, 0xFE0B, "ruwido austria gmbh"),
        UUID16(	Type.Member, 0xFE0C, "Procter & Gamble"),
        UUID16(	Type.Member, 0xFE0D, "Procter & Gamble"),
        UUID16(	Type.Member, 0xFE0E, "Setec Pty Ltd"),
        UUID16(	Type.Member, 0xFE0F, "Signify Netherlands B.V. (formerly Philips Lighting B.V.)"),
        UUID16(	Type.Member, 0xFE10, "LAPIS Technology Co., Ltd."),
        UUID16(	Type.Member, 0xFE11, "GMC-I Messtechnik GmbH"),
        UUID16(	Type.Member, 0xFE12, "M-Way Solutions GmbH"),
        UUID16(	Type.Member, 0xFE13, "Apple Inc."),
        UUID16(	Type.Member, 0xFE14, "Flextronics International USA Inc."),
        UUID16(	Type.Member, 0xFE15, "Amazon.com Services, Inc.."),
        UUID16(	Type.Member, 0xFE16, "Footmarks, Inc."),
        UUID16(	Type.Member, 0xFE17, "Telit Wireless Solutions GmbH"),
        UUID16(	Type.Member, 0xFE18, "Runtime, Inc."),
        UUID16(	Type.Member, 0xFE19, "Google, Inc"),
        UUID16(	Type.Member, 0xFE1A, "Tyto Life LLC"),
        UUID16(	Type.Member, 0xFE1B, "Tyto Life LLC"),
        UUID16(	Type.Member, 0xFE1C, "NetMedia, Inc."),
        UUID16(	Type.Member, 0xFE1D, "Illuminati Instrument Corporation"),
        UUID16(	Type.Member, 0xFE1E, "Smart Innovations Co., Ltd"),
        UUID16(	Type.Member, 0xFE1F, "Garmin International, Inc."),
        UUID16(	Type.Member, 0xFE20, "Emerson"),
        UUID16(	Type.Member, 0xFE21, "Bose Corporation"),
        UUID16(	Type.Member, 0xFE22, "Zoll Medical Corporation"),
        UUID16(	Type.Member, 0xFE23, "Zoll Medical Corporation"),
        UUID16(	Type.Member, 0xFE24, "August Home Inc"),
        UUID16(	Type.Member, 0xFE25, "Apple, Inc."),
        UUID16(	Type.Member, 0xFE26, "Google"),
        UUID16(	Type.Member, 0xFE27, "Google"),
        UUID16(	Type.Member, 0xFE28, "Ayla Networks"),
        UUID16(	Type.Member, 0xFE29, "Gibson Innovations"),
        UUID16(	Type.Member, 0xFE2A, "DaisyWorks, Inc."),
        UUID16(	Type.Member, 0xFE2B, "ITT Industries"),
        UUID16(	Type.Member, 0xFE2C, "Google"),
        UUID16(	Type.Member, 0xFE2D, "SMART INNOVATION Co.,Ltd"),
        UUID16(	Type.Member, 0xFE2E, "ERi,Inc."),
        UUID16(	Type.Member, 0xFE2F, "CRESCO Wireless, Inc"),
        UUID16(	Type.Member, 0xFE30, "Volkswagen AG"),
        UUID16(	Type.Member, 0xFE31, "Volkswagen AG"),
        UUID16(	Type.Member, 0xFE32, "Pro-Mark, Inc."),
        UUID16(	Type.Member, 0xFE33, "CHIPOLO d.o.o."),
        UUID16(	Type.Member, 0xFE34, "SmallLoop LLC"),
        UUID16(	Type.Member, 0xFE35, "HUAWEI Technologies Co., Ltd"),
        UUID16(	Type.Member, 0xFE36, "HUAWEI Technologies Co., Ltd"),
        UUID16(	Type.Member, 0xFE37, "Spaceek LTD"),
        UUID16(	Type.Member, 0xFE38, "Spaceek LTD"),
        UUID16(	Type.Member, 0xFE39, "TTS Tooltechnic Systems AG & Co. KG"),
        UUID16(	Type.Member, 0xFE3A, "TTS Tooltechnic Systems AG & Co. KG"),
        UUID16(	Type.Member, 0xFE3B, "Dolby Laboratories"),
        UUID16(	Type.Member, 0xFE3C, "alibaba"),
        UUID16(	Type.Member, 0xFE3D, "BD Medical"),
        UUID16(	Type.Member, 0xFE3E, "BD Medical"),
        UUID16(	Type.Member, 0xFE3F, "Friday Labs Limited"),
        UUID16(	Type.Member, 0xFE40, "Inugo Systems Limited"),
        UUID16(	Type.Member, 0xFE41, "Inugo Systems Limited"),
        UUID16(	Type.Member, 0xFE42, "Nets A/S"),
        UUID16(	Type.Member, 0xFE43, "Andreas Stihl AG & Co. KG"),
        UUID16(	Type.Member, 0xFE44, "SK Telecom"),
        UUID16(	Type.Member, 0xFE45, "Snapchat Inc"),
        UUID16(	Type.Member, 0xFE46, "B&O Play A/S"),
        UUID16(	Type.Member, 0xFE47, "General Motors"),
        UUID16(	Type.Member, 0xFE48, "General Motors"),
        UUID16(	Type.Member, 0xFE49, "SenionLab AB"),
        UUID16(	Type.Member, 0xFE4A, "OMRON HEALTHCARE Co., Ltd."),
        UUID16(	Type.Member, 0xFE4B, "Signify Netherlands B.V. (formerly Philips Lighting B.V.)"),
        UUID16(	Type.Member, 0xFE4C, "Volkswagen AG"),
        UUID16(	Type.Member, 0xFE4D, "Casambi Technologies Oy"),
        UUID16(	Type.Member, 0xFE4E, "NTT docomo"),
        UUID16(	Type.Member, 0xFE4F, "Molekule, Inc."),
        UUID16(	Type.Member, 0xFE50, "Google Inc."),
        UUID16(	Type.Member, 0xFE51, "SRAM"),
        UUID16(	Type.Member, 0xFE52, "SetPoint Medical"),
        UUID16(	Type.Member, 0xFE53, "3M"),
        UUID16(	Type.Member, 0xFE54, "Motiv, Inc."),
        UUID16(	Type.Member, 0xFE55, "Google Inc."),
        UUID16(	Type.Member, 0xFE56, "Google Inc."),
        UUID16(	Type.Member, 0xFE57, "Dotted Labs"),
        UUID16(	Type.Member, 0xFE58, "Nordic Semiconductor ASA"),
        UUID16(	Type.Member, 0xFE59, "Nordic Semiconductor ASA"),
        UUID16(	Type.Member, 0xFE5A, "Cronologics Corporation"),
        UUID16(	Type.Member, 0xFE5B, "GT-tronics HK Ltd"),
        UUID16(	Type.Member, 0xFE5C, "million hunters GmbH"),
        UUID16(	Type.Member, 0xFE5D, "Grundfos A/S"),
        UUID16(	Type.Member, 0xFE5E, "Plastc Corporation"),
        UUID16(	Type.Member, 0xFE5F, "Eyefi, Inc."),
        UUID16(	Type.Member, 0xFE60, "Lierda Science & Technology Group Co., Ltd."),
        UUID16(	Type.Member, 0xFE61, "Logitech International SA"),
        UUID16(	Type.Member, 0xFE62, "Indagem Tech LLC"),
        UUID16(	Type.Member, 0xFE63, "Connected Yard, Inc."),
        UUID16(	Type.Member, 0xFE64, "Siemens AG"),
        UUID16(	Type.Member, 0xFE65, "CHIPOLO d.o.o."),
        UUID16(	Type.Member, 0xFE66, "Intel Corporation"),
        UUID16(	Type.Member, 0xFE67, "Lab Sensor Solutions"),
        UUID16(	Type.Member, 0xFE68, "Qualcomm Life Inc"),
        UUID16(	Type.Member, 0xFE69, "Qualcomm Life Inc"),
        UUID16(	Type.Member, 0xFE6A, "Kontakt Micro-Location Sp. z o.o."),
        UUID16(	Type.Member, 0xFE6B, "TASER International, Inc."),
        UUID16(	Type.Member, 0xFE6C, "TASER International, Inc."),
        UUID16(	Type.Member, 0xFE6D, "The University of Tokyo"),
        UUID16(	Type.Member, 0xFE6E, "The University of Tokyo"),
        UUID16(	Type.Member, 0xFE6F, "LINE Corporation"),
        UUID16(	Type.Member, 0xFE70, "Beijing Jingdong Century Trading Co., Ltd."),
        UUID16(	Type.Member, 0xFE71, "Plume Design Inc"),
        UUID16(	Type.Member, 0xFE72, "Abbott (formerly St. Jude Medical, Inc.)"),
        UUID16(	Type.Member, 0xFE73, "Abbott (formerly St. Jude Medical, Inc.)"),
        UUID16(	Type.Member, 0xFE74, "unwire"),
        UUID16(	Type.Member, 0xFE75, "TangoMe"),
        UUID16(	Type.Member, 0xFE76, "TangoMe"),
        UUID16(	Type.Member, 0xFE77, "Hewlett-Packard Company"),
        UUID16(	Type.Member, 0xFE78, "Hewlett-Packard Company"),
        UUID16(	Type.Member, 0xFE79, "Zebra Technologies"),
        UUID16(	Type.Member, 0xFE7A, "Bragi GmbH"),
        UUID16(	Type.Member, 0xFE7B, "Orion Labs, Inc."),
        UUID16(	Type.Member, 0xFE7C, "Telit Wireless Solutions (Formerly Stollmann E+V GmbH)"),
        UUID16(	Type.Member, 0xFE7D, "Aterica Health Inc."),
        UUID16(	Type.Member, 0xFE7E, "Awear Solutions Ltd"),
        UUID16(	Type.Member, 0xFE7F, "Doppler Lab"),
        UUID16(	Type.Member, 0xFE80, "Doppler Lab"),
        UUID16(	Type.Member, 0xFE81, "Medtronic Inc."),
        UUID16(	Type.Member, 0xFE82, "Medtronic Inc."),
        UUID16(	Type.Member, 0xFE83, "Blue Bite"),
        UUID16(	Type.Member, 0xFE84, "RF Digital Corp"),
        UUID16(	Type.Member, 0xFE85, "RF Digital Corp"),
        UUID16(	Type.Member, 0xFE86, "HUAWEI Technologies Co., Ltd. ( 华为技术有限公司 )"),
        UUID16(	Type.Member, 0xFE87, "Qingdao Yeelink Information Technology Co., Ltd. ( 青岛亿联客信息技术有限公司 )"),
        UUID16(	Type.Member, 0xFE88, "SALTO SYSTEMS S.L."),
        UUID16(	Type.Member, 0xFE89, "B&O Play A/S"),
        UUID16(	Type.Member, 0xFE8A, "Apple, Inc."),
        UUID16(	Type.Member, 0xFE8B, "Apple, Inc."),
        UUID16(	Type.Member, 0xFE8C, "TRON Forum"),
        UUID16(	Type.Member, 0xFE8D, "Interaxon Inc."),
        UUID16(	Type.Member, 0xFE8E, "ARM Ltd"),
        UUID16(	Type.Member, 0xFE8F, "CSR"),
        UUID16(	Type.Member, 0xFE90, "JUMA"),
        UUID16(	Type.Member, 0xFE91, "Shanghai Imilab Technology Co.,Ltd"),
        UUID16(	Type.Member, 0xFE92, "Jarden Safety & Security"),
        UUID16(	Type.Member, 0xFE93, "OttoQ In"),
        UUID16(	Type.Member, 0xFE94, "OttoQ In"),
        UUID16(	Type.Member, 0xFE95, "Xiaomi Inc."),
        UUID16(	Type.Member, 0xFE96, "Tesla Motors Inc."),
        UUID16(	Type.Member, 0xFE97, "Tesla Motors Inc."),
        UUID16(	Type.Member, 0xFE98, "Currant Inc"),
        UUID16(	Type.Member, 0xFE99, "Currant Inc"),
        UUID16(	Type.Member, 0xFE9A, "Estimote"),
        UUID16(	Type.Member, 0xFE9B, "Samsara Networks, Inc"),
        UUID16(	Type.Member, 0xFE9C, "GSI Laboratories, Inc."),
        UUID16(	Type.Member, 0xFE9D, "Mobiquity Networks Inc"),
        UUID16(	Type.Member, 0xFE9E, "Dialog Semiconductor B.V."),
        UUID16(	Type.Member, 0xFE9F, "Google"),
        UUID16(	Type.Member, 0xFEA0, "Google"),
        UUID16(	Type.Member, 0xFEA1, "Intrepid Control Systems, Inc."),
        UUID16(	Type.Member, 0xFEA2, "Intrepid Control Systems, Inc."),
        UUID16(	Type.Member, 0xFEA3, "ITT Industries"),
        UUID16(	Type.Member, 0xFEA4, "Paxton Access Ltd"),
        UUID16(	Type.Member, 0xFEA5, "GoPro, Inc."),
        UUID16(	Type.Member, 0xFEA6, "GoPro, Inc."),
        UUID16(	Type.Member, 0xFEA7, "UTC Fire and Security"),
        UUID16(	Type.Member, 0xFEA8, "Savant Systems LLC"),
        UUID16(	Type.Member, 0xFEA9, "Savant Systems LLC"),
        UUID16(	Type.Member, 0xFEAA, "Google"),
        UUID16(	Type.Member, 0xFEAB, "Nokia"),
        UUID16(	Type.Member, 0xFEAC, "Nokia"),
        UUID16(	Type.Member, 0xFEAD, "Nokia"),
        UUID16(	Type.Member, 0xFEAE, "Nokia"),
        UUID16(	Type.Member, 0xFEAF, "Nest Labs Inc"),
        UUID16(	Type.Member, 0xFEB0, "Nest Labs Inc"),
        UUID16(	Type.Member, 0xFEB1, "Electronics Tomorrow Limited"),
        UUID16(	Type.Member, 0xFEB2, "Microsoft Corporation"),
        UUID16(	Type.Member, 0xFEB3, "Taobao"),
        UUID16(	Type.Member, 0xFEB4, "WiSilica Inc."),
        UUID16(	Type.Member, 0xFEB5, "WiSilica Inc."),
        UUID16(	Type.Member, 0xFEB6, "Vencer Co., Ltd"),
        UUID16(	Type.Member, 0xFEB7, "Facebook, Inc."),
        UUID16(	Type.Member, 0xFEB8, "Facebook, Inc."),
        UUID16(	Type.Member, 0xFEB9, "LG Electronics"),
        UUID16(	Type.Member, 0xFEBA, "Tencent Holdings Limited"),
        UUID16(	Type.Member, 0xFEBB, "adafruit industries"),
        UUID16(	Type.Member, 0xFEBC, "Dexcom Inc"),
        UUID16(	Type.Member, 0xFEBD, "Clover Network, Inc"),
        UUID16(	Type.Member, 0xFEBE, "Bose Corporation"),
        UUID16(	Type.Member, 0xFEBF, "Nod, Inc."),
        UUID16(	Type.Member, 0xFEC0, "KDDI Corporation"),
        UUID16(	Type.Member, 0xFEC1, "KDDI Corporation"),
        UUID16(	Type.Member, 0xFEC2, "Blue Spark Technologies, Inc."),
        UUID16(	Type.Member, 0xFEC3, "360fly, Inc."),
        UUID16(	Type.Member, 0xFEC4, "PLUS Location Systems"),
        UUID16(	Type.Member, 0xFEC5, "Realtek Semiconductor Corp."),
        UUID16(	Type.Member, 0xFEC6, "Kocomojo, LLC"),
        UUID16(	Type.Member, 0xFEC7, "Apple, Inc."),
        UUID16(	Type.Member, 0xFEC8, "Apple, Inc."),
        UUID16(	Type.Member, 0xFEC9, "Apple, Inc."),
        UUID16(	Type.Member, 0xFECA, "Apple, Inc."),
        UUID16(	Type.Member, 0xFECB, "Apple, Inc."),
        UUID16(	Type.Member, 0xFECC, "Apple, Inc."),
        UUID16(	Type.Member, 0xFECD, "Apple, Inc."),
        UUID16(	Type.Member, 0xFECE, "Apple, Inc."),
        UUID16(	Type.Member, 0xFECF, "Apple, Inc."),
        UUID16(	Type.Member, 0xFED0, "Apple, Inc."),
        UUID16(	Type.Member, 0xFED1, "Apple, Inc."),
        UUID16(	Type.Member, 0xFED2, "Apple, Inc."),
        UUID16(	Type.Member, 0xFED3, "Apple, Inc."),
        UUID16(	Type.Member, 0xFED4, "Apple, Inc."),
        UUID16(	Type.Member, 0xFED5, "Plantronics Inc."),
        UUID16(	Type.Member, 0xFED6, "Broadcom"),
        UUID16(	Type.Member, 0xFED7, "Broadcom"),
        UUID16(	Type.Member, 0xFED8, "Google"),
        UUID16(	Type.Member, 0xFED9, "Pebble Technology Corporation"),
        UUID16(	Type.Member, 0xFEDA, "ISSC Technologies Corp."),
        UUID16(	Type.Member, 0xFEDB, "Perka, Inc."),
        UUID16(	Type.Member, 0xFEDC, "Jawbone"),
        UUID16(	Type.Member, 0xFEDD, "Jawbone"),
        UUID16(	Type.Member, 0xFEDE, "Coin, Inc."),
        UUID16(	Type.Member, 0xFEDF, "Design SHIFT"),
        UUID16(	Type.Member, 0xFEE0, "Anhui Huami Information Technology Co., Ltd."),
        UUID16(	Type.Member, 0xFEE1, "Anhui Huami Information Technology Co., Ltd."),
        UUID16(	Type.Member, 0xFEE2, "Anki, Inc."),
        UUID16(	Type.Member, 0xFEE3, "Anki, Inc."),
        UUID16(	Type.Member, 0xFEE4, "Nordic Semiconductor ASA"),
        UUID16(	Type.Member, 0xFEE5, "Nordic Semiconductor ASA"),
        UUID16(	Type.Member, 0xFEE6, "Silvair, Inc."),
        UUID16(	Type.Member, 0xFEE7, "Tencent Holdings Limited."),
        UUID16(	Type.Member, 0xFEE8, "Quintic Corp."),
        UUID16(	Type.Member, 0xFEE9, "Quintic Corp."),
        UUID16(	Type.Member, 0xFEEA, "Swirl Networks, Inc."),
        UUID16(	Type.Member, 0xFEEB, "Swirl Networks, Inc."),
        UUID16(	Type.Member, 0xFEEC, "Tile, Inc."),
        UUID16(	Type.Member, 0xFEED, "Tile, Inc."),
        UUID16(	Type.Member, 0xFEEE, "Polar Electro Oy"),
        UUID16(	Type.Member, 0xFEEF, "Polar Electro Oy"),
        UUID16(	Type.Member, 0xFEF0, "Intel"),
        UUID16(	Type.Member, 0xFEF1, "CSR"),
        UUID16(	Type.Member, 0xFEF2, "CSR"),
        UUID16(	Type.Member, 0xFEF3, "Google"),
        UUID16(	Type.Member, 0xFEF4, "Google"),
        UUID16(	Type.Member, 0xFEF5, "Dialog Semiconductor GmbH"),
        UUID16(	Type.Member, 0xFEF6, "Wicentric, Inc."),
        UUID16(	Type.Member, 0xFEF7, "Aplix Corporation"),
        UUID16(	Type.Member, 0xFEF8, "Aplix Corporation"),
        UUID16(	Type.Member, 0xFEF9, "PayPal, Inc."),
        UUID16(	Type.Member, 0xFEFA, "PayPal, Inc."),
        UUID16(	Type.Member, 0xFEFB, "Telit Wireless Solutions (Formerly Stollmann E+V GmbH)"),
        UUID16(	Type.Member, 0xFEFC, "Gimbal, Inc."),
        UUID16(	Type.Member, 0xFEFD, "Gimbal, Inc."),
        UUID16(	Type.Member, 0xFEFE, "GN ReSound A/S"),
        UUID16(	Type.Member, 0xFEFF, "GN Netcom"),
        UUID16(	Type.Characteristic, 0x2A00, "Device Name"),
        UUID16(	Type.Characteristic, 0x2A01, "Appearance"),
        UUID16(	Type.Characteristic, 0x2A02, "Peripheral Privacy Flag"),
        UUID16(	Type.Characteristic, 0x2A03, "Reconnection Address"),
        UUID16(	Type.Characteristic, 0x2A04, "Peripheral Preferred Connection Parameters"),
        UUID16(	Type.Characteristic, 0x2A05, "Service Changed"),
        UUID16(	Type.Characteristic, 0x2A06, "Alert Level"),
        UUID16(	Type.Characteristic, 0x2A07, "Tx Power Level"),
        UUID16(	Type.Characteristic, 0x2A08, "Date Time"),
        UUID16(	Type.Characteristic, 0x2A09, "Day of Week"),
        UUID16(	Type.Characteristic, 0x2A0A, "Day Date Time"),
        UUID16(	Type.Characteristic, 0x2A0C, "Exact Time 256"),
        UUID16(	Type.Characteristic, 0x2A0D, "DST Offset"),
        UUID16(	Type.Characteristic, 0x2A0E, "Time Zone"),
        UUID16(	Type.Characteristic, 0x2A0F, "Local Time Information"),
        UUID16(	Type.Characteristic, 0x2A11, "Time with DST"),
        UUID16(	Type.Characteristic, 0x2A12, "Time Accuracy"),
        UUID16(	Type.Characteristic, 0x2A13, "Time Source"),
        UUID16(	Type.Characteristic, 0x2A14, "Reference Time Information"),
        UUID16(	Type.Characteristic, 0x2A16, "Time Update Control Point"),
        UUID16(	Type.Characteristic, 0x2A17, "Time Update State"),
        UUID16(	Type.Characteristic, 0x2A18, "Glucose Measurement"),
        UUID16(	Type.Characteristic, 0x2A19, "Battery Level"),
        UUID16(	Type.Characteristic, 0x2A1C, "Temperature Measurement"),
        UUID16(	Type.Characteristic, 0x2A1D, "Temperature Type"),
        UUID16(	Type.Characteristic, 0x2A1E, "Intermediate Temperature"),
        UUID16(	Type.Characteristic, 0x2A21, "Measurement Interval"),
        UUID16(	Type.Characteristic, 0x2A22, "Boot Keyboard Input Report"),
        UUID16(	Type.Characteristic, 0x2A23, "System ID"),
        UUID16(	Type.Characteristic, 0x2A24, "Model Number String"),
        UUID16(	Type.Characteristic, 0x2A25, "Serial Number String"),
        UUID16(	Type.Characteristic, 0x2A26, "Firmware Revision String"),
        UUID16(	Type.Characteristic, 0x2A27, "Hardware Revision String"),
        UUID16(	Type.Characteristic, 0x2A28, "Software Revision String"),
        UUID16(	Type.Characteristic, 0x2A29, "Manufacturer Name String"),
        UUID16(	Type.Characteristic, 0x2A2A, "IEEE 11073-20601 Regulatory Certification Data List"),
        UUID16(	Type.Characteristic, 0x2A2B, "Current Time"),
        UUID16(	Type.Characteristic, 0x2A31, "Scan Refresh"),
        UUID16(	Type.Characteristic, 0x2A32, "Boot Keyboard Output Report"),
        UUID16(	Type.Characteristic, 0x2A33, "Boot Mouse Input Report"),
        UUID16(	Type.Characteristic, 0x2A34, "Glucose Measurement Context"),
        UUID16(	Type.Characteristic, 0x2A35, "Blood Pressure Measurement"),
        UUID16(	Type.Characteristic, 0x2A36, "Intermediate Cuff Pressure"),
        UUID16(	Type.Characteristic, 0x2A37, "Heart Rate Measurement"),
        UUID16(	Type.Characteristic, 0x2A38, "Body Sensor Location"),
        UUID16(	Type.Characteristic, 0x2A39, "Heart Rate Control Point"),
        UUID16(	Type.Characteristic, 0x2A3F, "Alert Status"),
        UUID16(	Type.Characteristic, 0x2A40, "Ringer Control Point"),
        UUID16(	Type.Characteristic, 0x2A41, "Ringer Setting"),
        UUID16(	Type.Characteristic, 0x2A42, "Alert Category ID Bit Mask"),
        UUID16(	Type.Characteristic, 0x2A43, "Alert Category ID"),
        UUID16(	Type.Characteristic, 0x2A44, "Alert Notification Control Point"),
        UUID16(	Type.Characteristic, 0x2A45, "Unread Alert Status"),
        UUID16(	Type.Characteristic, 0x2A46, "New Alert"),
        UUID16(	Type.Characteristic, 0x2A47, "Supported New Alert Category"),
        UUID16(	Type.Characteristic, 0x2A48, "Supported Unread Alert Category"),
        UUID16(	Type.Characteristic, 0x2A49, "Blood Pressure Feature"),
        UUID16(	Type.Characteristic, 0x2A4A, "HID Information"),
        UUID16(	Type.Characteristic, 0x2A4B, "Report Map"),
        UUID16(	Type.Characteristic, 0x2A4C, "HID Control Point"),
        UUID16(	Type.Characteristic, 0x2A4D, "Report"),
        UUID16(	Type.Characteristic, 0x2A4E, "Protocol Mode"),
        UUID16(	Type.Characteristic, 0x2A4F, "Scan Interval Window"),
        UUID16(	Type.Characteristic, 0x2A50, "PnP ID"),
        UUID16(	Type.Characteristic, 0x2A51, "Glucose Feature"),
        UUID16(	Type.Characteristic, 0x2A52, "Record Access Control Point"),
        UUID16(	Type.Characteristic, 0x2A53, "RSC Measurement"),
        UUID16(	Type.Characteristic, 0x2A54, "RSC Feature"),
        UUID16(	Type.Characteristic, 0x2A55, "SC Control Point"),
        UUID16(	Type.Characteristic, 0x2A5A, "Aggregate"),
        UUID16(	Type.Characteristic, 0x2A5B, "CSC Measurement"),
        UUID16(	Type.Characteristic, 0x2A5C, "CSC Feature"),
        UUID16(	Type.Characteristic, 0x2A5D, "Sensor Location"),
        UUID16(	Type.Characteristic, 0x2A5E, "PLX Spot-Check Measurement"),
        UUID16(	Type.Characteristic, 0x2A5F, "PLX Continuous Measurement"),
        UUID16(	Type.Characteristic, 0x2A60, "PLX Features"),
        UUID16(	Type.Characteristic, 0x2A63, "Cycling Power Measurement"),
        UUID16(	Type.Characteristic, 0x2A64, "Cycling Power Vector"),
        UUID16(	Type.Characteristic, 0x2A65, "Cycling Power Feature"),
        UUID16(	Type.Characteristic, 0x2A66, "Cycling Power Control Point"),
        UUID16(	Type.Characteristic, 0x2A67, "Location and Speed"),
        UUID16(	Type.Characteristic, 0x2A68, "Navigation"),
        UUID16(	Type.Characteristic, 0x2A69, "Position Quality"),
        UUID16(	Type.Characteristic, 0x2A6A, "LN Feature"),
        UUID16(	Type.Characteristic, 0x2A6B, "LN Control Point"),
        UUID16(	Type.Characteristic, 0x2A6C, "Elevation"),
        UUID16(	Type.Characteristic, 0x2A6D, "Pressure"),
        UUID16(	Type.Characteristic, 0x2A6E, "Temperature"),
        UUID16(	Type.Characteristic, 0x2A6F, "Humidity"),
        UUID16(	Type.Characteristic, 0x2A70, "True Wind Speed"),
        UUID16(	Type.Characteristic, 0x2A71, "True Wind Direction"),
        UUID16(	Type.Characteristic, 0x2A72, "Apparent Wind Speed"),
        UUID16(	Type.Characteristic, 0x2A73, "Apparent Wind Direction"),
        UUID16(	Type.Characteristic, 0x2A74, "Gust Factor"),
        UUID16(	Type.Characteristic, 0x2A75, "Pollen Concentration"),
        UUID16(	Type.Characteristic, 0x2A76, "UV Index"),
        UUID16(	Type.Characteristic, 0x2A77, "Irradiance"),
        UUID16(	Type.Characteristic, 0x2A78, "Rainfall"),
        UUID16(	Type.Characteristic, 0x2A79, "Wind Chill"),
        UUID16(	Type.Characteristic, 0x2A7A, "Heat Index"),
        UUID16(	Type.Characteristic, 0x2A7B, "Dew Point"),
        UUID16(	Type.Characteristic, 0x2A7D, "Descriptor Value Changed"),
        UUID16(	Type.Characteristic, 0x2A7E, "Aerobic Heart Rate Lower Limit"),
        UUID16(	Type.Characteristic, 0x2A7F, "Aerobic Threshold"),
        UUID16(	Type.Characteristic, 0x2A80, "Age"),
        UUID16(	Type.Characteristic, 0x2A81, "Anaerobic Heart Rate Lower Limit"),
        UUID16(	Type.Characteristic, 0x2A82, "Anaerobic Heart Rate Upper Limit"),
        UUID16(	Type.Characteristic, 0x2A83, "Anaerobic Threshold"),
        UUID16(	Type.Characteristic, 0x2A84, "Aerobic Heart Rate Upper Limit"),
        UUID16(	Type.Characteristic, 0x2A85, "Date of Birth"),
        UUID16(	Type.Characteristic, 0x2A86, "Date of Threshold Assessment"),
        UUID16(	Type.Characteristic, 0x2A87, "Email Address"),
        UUID16(	Type.Characteristic, 0x2A88, "Fat Burn Heart Rate Lower Limit"),
        UUID16(	Type.Characteristic, 0x2A89, "Fat Burn Heart Rate Upper Limit"),
        UUID16(	Type.Characteristic, 0x2A8A, "First Name"),
        UUID16(	Type.Characteristic, 0x2A8B, "Five Zone Heart Rate Limits"),
        UUID16(	Type.Characteristic, 0x2A8C, "Gender"),
        UUID16(	Type.Characteristic, 0x2A8D, "Heart Rate Max"),
        UUID16(	Type.Characteristic, 0x2A8E, "Height"),
        UUID16(	Type.Characteristic, 0x2A8F, "Hip Circumference"),
        UUID16(	Type.Characteristic, 0x2A90, "Last Name"),
        UUID16(	Type.Characteristic, 0x2A91, "Maximum Recommended Heart Rate"),
        UUID16(	Type.Characteristic, 0x2A92, "Resting Heart Rate"),
        UUID16(	Type.Characteristic, 0x2A93, "Sport Type for Aerobic and Anaerobic Thresholds"),
        UUID16(	Type.Characteristic, 0x2A94, "Three Zone Heart Rate Limits"),
        UUID16(	Type.Characteristic, 0x2A95, "Two Zone Heart Rate Limits"),
        UUID16(	Type.Characteristic, 0x2A96, "VO2 Max"),
        UUID16(	Type.Characteristic, 0x2A97, "Waist Circumference"),
        UUID16(	Type.Characteristic, 0x2A98, "Weight"),
        UUID16(	Type.Characteristic, 0x2A99, "Database Change Increment"),
        UUID16(	Type.Characteristic, 0x2A9A, "User Index"),
        UUID16(	Type.Characteristic, 0x2A9B, "Body Composition Feature"),
        UUID16(	Type.Characteristic, 0x2A9C, "Body Composition Measurement"),
        UUID16(	Type.Characteristic, 0x2A9D, "Weight Measurement"),
        UUID16(	Type.Characteristic, 0x2A9E, "Weight Scale Feature"),
        UUID16(	Type.Characteristic, 0x2A9F, "User Control Point"),
        UUID16(	Type.Characteristic, 0x2AA0, "Magnetic Flux Density - 2D"),
        UUID16(	Type.Characteristic, 0x2AA1, "Magnetic Flux Density - 3D"),
        UUID16(	Type.Characteristic, 0x2AA2, "Language"),
        UUID16(	Type.Characteristic, 0x2AA3, "Barometric Pressure Trend"),
        UUID16(	Type.Characteristic, 0x2AA4, "Bond Management Control Point"),
        UUID16(	Type.Characteristic, 0x2AA5, "Bond Management Feature"),
        UUID16(	Type.Characteristic, 0x2AA6, "Central Address Resolution"),
        UUID16(	Type.Characteristic, 0x2AA7, "CGM Measurement"),
        UUID16(	Type.Characteristic, 0x2AA8, "CGM Feature"),
        UUID16(	Type.Characteristic, 0x2AA9, "CGM Status"),
        UUID16(	Type.Characteristic, 0x2AAA, "CGM Session Start Time"),
        UUID16(	Type.Characteristic, 0x2AAB, "CGM Session Run Time"),
        UUID16(	Type.Characteristic, 0x2AAC, "CGM Specific Ops Control Point"),
        UUID16(	Type.Characteristic, 0x2AAD, "Indoor Positioning Configuration"),
        UUID16(	Type.Characteristic, 0x2AAE, "Latitude"),
        UUID16(	Type.Characteristic, 0x2AAF, "Longitude"),
        UUID16(	Type.Characteristic, 0x2AB0, "Local North Coordinate"),
        UUID16(	Type.Characteristic, 0x2AB1, "Local East Coordinate"),
        UUID16(	Type.Characteristic, 0x2AB2, "Floor Number"),
        UUID16(	Type.Characteristic, 0x2AB3, "Altitude"),
        UUID16(	Type.Characteristic, 0x2AB4, "Uncertainty"),
        UUID16(	Type.Characteristic, 0x2AB5, "Location Name"),
        UUID16(	Type.Characteristic, 0x2AB6, "URI"),
        UUID16(	Type.Characteristic, 0x2AB7, "HTTP Headers"),
        UUID16(	Type.Characteristic, 0x2AB8, "HTTP Status Code"),
        UUID16(	Type.Characteristic, 0x2AB9, "HTTP Entity Body"),
        UUID16(	Type.Characteristic, 0x2ABA, "HTTP Control Point"),
        UUID16(	Type.Characteristic, 0x2ABB, "HTTPS Security"),
        UUID16(	Type.Characteristic, 0x2ABC, "TDS Control Point"),
        UUID16(	Type.Characteristic, 0x2ABD, "OTS Feature"),
        UUID16(	Type.Characteristic, 0x2ABE, "object name"),
        UUID16(	Type.Characteristic, 0x2ABF, "object type"),
        UUID16(	Type.Characteristic, 0x2AC0, "object size"),
        UUID16(	Type.Characteristic, 0x2AC1, "object first created"),
        UUID16(	Type.Characteristic, 0x2AC2, "object last modified"),
        UUID16(	Type.Characteristic, 0x2AC3, "object ID"),
        UUID16(	Type.Characteristic, 0x2AC4, "object properties"),
        UUID16(	Type.Characteristic, 0x2AC5, "object actioncontrol point"),
        UUID16(	Type.Characteristic, 0x2AC6, "object list control point"),
        UUID16(	Type.Characteristic, 0x2AC7, "object list filter"),
        UUID16(	Type.Characteristic, 0x2AC8, "object changed"),
        UUID16(	Type.Characteristic, 0x2AC9, "Resolvable Private Address Only"),
        UUID16(	Type.Characteristic, 0x2ACA, "Unspecified"),
        UUID16(	Type.Characteristic, 0x2ACB, "Directory Listing"),
        UUID16(	Type.Characteristic, 0x2ACC, "Fitness Machine Feature"),
        UUID16(	Type.Characteristic, 0x2ACD, "Treadmill Data"),
        UUID16(	Type.Characteristic, 0x2ACE, "Cross Trainer Data"),
        UUID16(	Type.Characteristic, 0x2ACF, "Step Climber Data"),
        UUID16(	Type.Characteristic, 0x2AD0, "Stair Climber Data"),
        UUID16(	Type.Characteristic, 0x2AD1, "Rower Data"),
        UUID16(	Type.Characteristic, 0x2AD2, "Indoor Bike Data"),
        UUID16(	Type.Characteristic, 0x2AD3, "Training Status"),
        UUID16(	Type.Characteristic, 0x2AD4, "Supported Speed Range"),
        UUID16(	Type.Characteristic, 0x2AD5, "Supported Inclination Range"),
        UUID16(	Type.Characteristic, 0x2AD6, "Supported Resistance Level Range"),
        UUID16(	Type.Characteristic, 0x2AD7, "Supported Heart Rate Range"),
        UUID16(	Type.Characteristic, 0x2AD8, "Supported Power Range"),
        UUID16(	Type.Characteristic, 0x2AD9, "Fitness Machine Control Point"),
        UUID16(	Type.Characteristic, 0x2ADA, "Fitness Machine Status"),
        UUID16(	Type.Characteristic, 0x2ADB, "Mesh Provisioning Data In"),
        UUID16(	Type.Characteristic, 0x2ADC, "Mesh Provisioning Data Out"),
        UUID16(	Type.Characteristic, 0x2ADD, "Mesh Proxy Data In"),
        UUID16(	Type.Characteristic, 0x2ADE, "Mesh Proxy Data Out"),
        UUID16(	Type.Characteristic, 0x2AE0, "Average Current"),
        UUID16(	Type.Characteristic, 0x2AE1, "Average Voltage"),
        UUID16(	Type.Characteristic, 0x2AE2, "Boolean"),
        UUID16(	Type.Characteristic, 0x2AE3, "Chromatic Distance From Planckian"),
        UUID16(	Type.Characteristic, 0x2AE4, "Chromaticity Coordinates"),
        UUID16(	Type.Characteristic, 0x2AE5, "Chromaticity in CCT And Duv Values"),
        UUID16(	Type.Characteristic, 0x2AE6, "Chromaticity Tolerance"),
        UUID16(	Type.Characteristic, 0x2AE7, "CIE 13.3-1995 Color Rendering Index"),
        UUID16(	Type.Characteristic, 0x2AE8, "Coefficient"),
        UUID16(	Type.Characteristic, 0x2AE9, "Correlated Color Temperature"),
        UUID16(	Type.Characteristic, 0x2AEA, "Count 16"),
        UUID16(	Type.Characteristic, 0x2AEB, "Count 24"),
        UUID16(	Type.Characteristic, 0x2AEC, "Country Code"),
        UUID16(	Type.Characteristic, 0x2AED, "Date UTC"),
        UUID16(	Type.Characteristic, 0x2AEE, "Electric Current"),
        UUID16(	Type.Characteristic, 0x2AEF, "Electric Current Range"),
        UUID16(	Type.Characteristic, 0x2AF0, "Electric Current Specification"),
        UUID16(	Type.Characteristic, 0x2AF1, "Electric Current Statistics"),
        UUID16(	Type.Characteristic, 0x2AF2, "Energy"),
        UUID16(	Type.Characteristic, 0x2AF3, "Energy In A Period Of Day"),
        UUID16(	Type.Characteristic, 0x2AF4, "Event Statistics"),
        UUID16(	Type.Characteristic, 0x2AF5, "Fixed String 16"),
        UUID16(	Type.Characteristic, 0x2AF6, "Fixed String 24"),
        UUID16(	Type.Characteristic, 0x2AF7, "Fixed String 36"),
        UUID16(	Type.Characteristic, 0x2AF8, "Fixed String 8"),
        UUID16(	Type.Characteristic, 0x2AF9, "Generic Level"),
        UUID16(	Type.Characteristic, 0x2AFA, "Global Trade Item Number"),
        UUID16(	Type.Characteristic, 0x2AFB, "Illuminance"),
        UUID16(	Type.Characteristic, 0x2AFC, "Luminous Efficacy"),
        UUID16(	Type.Characteristic, 0x2AFD, "Luminous Energy"),
        UUID16(	Type.Characteristic, 0x2AFE, "Luminous Exposure"),
        UUID16(	Type.Characteristic, 0x2AFF, "Luminous Flux"),
        UUID16(	Type.Characteristic, 0x2B00, "Luminous Flux Range"),
        UUID16(	Type.Characteristic, 0x2B01, "Luminous Intensity"),
        UUID16(	Type.Characteristic, 0x2B02, "Mass Flow"),
        UUID16(	Type.Characteristic, 0x2B03, "Perceived Lightness"),
        UUID16(	Type.Characteristic, 0x2B04, "Percentage 8"),
        UUID16(	Type.Characteristic, 0x2B05, "Power"),
        UUID16(	Type.Characteristic, 0x2B06, "Power Specification"),
        UUID16(	Type.Characteristic, 0x2B07, "Relative Runtime In A Current Range"),
        UUID16(	Type.Characteristic, 0x2B08, "Relative Runtime In A Generic Level Range"),
        UUID16(	Type.Characteristic, 0x2B09, "Relative Value In A Voltage Range"),
        UUID16(	Type.Characteristic, 0x2B0A, "Relative Value In An Illuminance Range"),
        UUID16(	Type.Characteristic, 0x2B0B, "Relative Value In A Period Of Day"),
        UUID16(	Type.Characteristic, 0x2B0C, "Relative Value In A Temperature Range"),
        UUID16(	Type.Characteristic, 0x2B0D, "Temperature 8"),
        UUID16(	Type.Characteristic, 0x2B0E, "Temperature 8 In A Period Of Day"),
        UUID16(	Type.Characteristic, 0x2B0F, "Temperature 8 Statistics"),
        UUID16(	Type.Characteristic, 0x2B10, "Temperature Range"),
        UUID16(	Type.Characteristic, 0x2B11, "Temperature Statistics"),
        UUID16(	Type.Characteristic, 0x2B12, "Time Decihour 8"),
        UUID16(	Type.Characteristic, 0x2B13, "Time Exponential 8"),
        UUID16(	Type.Characteristic, 0x2B14, "Time Hour 24"),
        UUID16(	Type.Characteristic, 0x2B15, "Time Millisecond 24"),
        UUID16(	Type.Characteristic, 0x2B16, "Time Second 16"),
        UUID16(	Type.Characteristic, 0x2B17, "Time Second 8"),
        UUID16(	Type.Characteristic, 0x2B18, "Voltage"),
        UUID16(	Type.Characteristic, 0x2B19, "Voltage Specification"),
        UUID16(	Type.Characteristic, 0x2B1A, "Voltage Statistics"),
        UUID16(	Type.Characteristic, 0x2B1B, "Volume Flow"),
        UUID16(	Type.Characteristic, 0x2B1C, "Chromaticity Coordinate"),
        UUID16(	Type.Characteristic, 0x2B1D, "RC Feature"),
        UUID16(	Type.Characteristic, 0x2B1E, "RC Settings"),
        UUID16(	Type.Characteristic, 0x2B1F, "Reconnection Configuration Control Point"),
        UUID16(	Type.Characteristic, 0x2B20, "IDD Status Changed"),
        UUID16(	Type.Characteristic, 0x2B21, "IDD Status"),
        UUID16(	Type.Characteristic, 0x2B22, "IDD Annunciation Status"),
        UUID16(	Type.Characteristic, 0x2B23, "IDD Features"),
        UUID16(	Type.Characteristic, 0x2B24, "IDD Status Reader Control Point"),
        UUID16(	Type.Characteristic, 0x2B25, "IDD Command Control Point"),
        UUID16(	Type.Characteristic, 0x2B26, "IDD Command Data"),
        UUID16(	Type.Characteristic, 0x2B27, "IDD Record Access Control Point"),
        UUID16(	Type.Characteristic, 0x2B28, "IDD History Data"),
        UUID16(	Type.Characteristic, 0x2B29, "Client Supported Features"),
        UUID16(	Type.Characteristic, 0x2B2A, "Database Hash"),
        UUID16(	Type.Characteristic, 0x2B2B, "BSS Control Point"),
        UUID16(	Type.Characteristic, 0x2B2C, "BSS Response"),
        UUID16(	Type.Characteristic, 0x2B2D, "Emergency ID"),
        UUID16(	Type.Characteristic, 0x2B2E, "Emergency Text"),
        UUID16(	Type.Characteristic, 0x2B34, "Enhanced Blood Pressure Measurement"),
        UUID16(	Type.Characteristic, 0x2B35, "Enhanced Intermediate Cuff Pressure"),
        UUID16(	Type.Characteristic, 0x2B36, "Blood Pressure Record"),
        UUID16(	Type.Characteristic, 0x2B38, "BR-EDR Handover Data"),
        UUID16(	Type.Characteristic, 0x2B39, "Bluetooth SIG Data"),
        UUID16(	Type.Characteristic, 0x2B3A, "Server Supported Features"),
        UUID16(	Type.Characteristic, 0x2B3B, "Physical Activity Monitor Features"),
        UUID16(	Type.Characteristic, 0x2B3C, "General Activity Instantaneous Data"),
        UUID16(	Type.Characteristic, 0x2B3D, "General Activity Summary Data"),
        UUID16(	Type.Characteristic, 0x2B3E, "CardioRespiratory Activity Instantaneous Data"),
        UUID16(	Type.Characteristic, 0x2B3F, "CardioRespiratory Activity Summary Data"),
        UUID16(	Type.Characteristic, 0x2B40, "Step Counter Activity Summary Data"),
        UUID16(	Type.Characteristic, 0x2B41, "Sleep Activity Instantaneous Data"),
        UUID16(	Type.Characteristic, 0x2B42, "Sleep Activity Summary Data"),
        UUID16(	Type.Characteristic, 0x2B43, "Physical Activity Monitor Control Point"),
        UUID16(	Type.Characteristic, 0x2B44, "Current Session"),
        UUID16(	Type.Characteristic, 0x2B45, "Session"),
        UUID16(	Type.Characteristic, 0x2B46, "Preferred Units"),
        UUID16(	Type.Characteristic, 0x2B47, "High Resolution Height"),
        UUID16(	Type.Characteristic, 0x2B48, "Middle Name"),
        UUID16(	Type.Characteristic, 0x2B49, "Stride Length"),
        UUID16(	Type.Characteristic, 0x2B4A, "Handedness"),
        UUID16(	Type.Characteristic, 0x2B4B, "Device Wearing Position"),
        UUID16(	Type.Characteristic, 0x2B4C, "Four Zone Heart Rate Limits"),
        UUID16(	Type.Characteristic, 0x2B4D, "High Intensity Exercise Threshold"),
        UUID16(	Type.Characteristic, 0x2B4E, "Activity Goal"),
        UUID16(	Type.Characteristic, 0x2B4F, "Sedentary Interval Notification"),
        UUID16(	Type.Characteristic, 0x2B50, "Caloric Intake"),
        UUID16(	Type.Characteristic, 0x2B77, "Audio Input State"),
        UUID16(	Type.Characteristic, 0x2B78, "Gain Settings Attribute"),
        UUID16(	Type.Characteristic, 0x2B79, "Audio Input Type"),
        UUID16(	Type.Characteristic, 0x2B7A, "Audio Input Status"),
        UUID16(	Type.Characteristic, 0x2B7B, "Audio Input Control Point"),
        UUID16(	Type.Characteristic, 0x2B7C, "Audio Input Description"),
        UUID16(	Type.Characteristic, 0x2B7D, "Volume State"),
        UUID16(	Type.Characteristic, 0x2B7E, "Volume Control Point"),
        UUID16(	Type.Characteristic, 0x2B7F, "Volume Flags"),
        UUID16(	Type.Characteristic, 0x2B80, "Offset State"),
        UUID16(	Type.Characteristic, 0x2B81, "Audio Location"),
        UUID16(	Type.Characteristic, 0x2B82, "Volume Offset Control Point"),
        UUID16(	Type.Characteristic, 0x2B83, "Audio Output Description"),
        UUID16(	Type.Characteristic, 0x2B84, "Set Identity Resolving Key Characteristic"),
        UUID16(	Type.Characteristic, 0x2B85, "Size Characteristic"),
        UUID16(	Type.Characteristic, 0x2B86, "Lock Characteristic"),
        UUID16(	Type.Characteristic, 0x2B87, "Rank Characteristic"),
        UUID16(	Type.Characteristic, 0x2B8E, "Device Time Feature"),
        UUID16(	Type.Characteristic, 0x2B8F, "Device Time Parameters"),
        UUID16(	Type.Characteristic, 0x2B90, "Device Time"),
        UUID16(	Type.Characteristic, 0x2B91, "Device Time Control Point"),
        UUID16(	Type.Characteristic, 0x2B92, "Time Change Log Data"),
        UUID16(	Type.Characteristic, 0x2B93, "Media Player Name"),
        UUID16(	Type.Characteristic, 0x2B94, "Media Player Icon Object ID"),
        UUID16(	Type.Characteristic, 0x2B95, "Media Player Icon URL"),
        UUID16(	Type.Characteristic, 0x2B96, "Track Changed"),
        UUID16(	Type.Characteristic, 0x2B97, "Track Title"),
        UUID16(	Type.Characteristic, 0x2B98, "Track Duration"),
        UUID16(	Type.Characteristic, 0x2B99, "Track Position"),
        UUID16(	Type.Characteristic, 0x2B9A, "Playback Speed"),
        UUID16(	Type.Characteristic, 0x2B9B, "Seeking Speed"),
        UUID16(	Type.Characteristic, 0x2B9C, "Current Track Segments Object ID"),
        UUID16(	Type.Characteristic, 0x2B9D, "Current Track Object ID"),
        UUID16(	Type.Characteristic, 0x2B9E, "Next Track Object ID"),
        UUID16(	Type.Characteristic, 0x2B9F, "Parent Group Object ID"),
        UUID16(	Type.Characteristic, 0x2BA0, "Current Group Object ID"),
        UUID16(	Type.Characteristic, 0x2BA1, "Playing Order"),
        UUID16(	Type.Characteristic, 0x2BA2, "Playing Orders Supported"),
        UUID16(	Type.Characteristic, 0x2BA3, "Media State"),
        UUID16(	Type.Characteristic, 0x2BA4, "Media Control Point"),
        UUID16(	Type.Characteristic, 0x2BA5, "Media Control Point Opcodes Supported"),
        UUID16(	Type.Characteristic, 0x2BA6, "Search Results Object ID"),
        UUID16(	Type.Characteristic, 0x2BA7, "Search Control Point"),
        UUID16(	Type.Characteristic, 0x2BA9, "Media Player Icon Object Type"),
        UUID16(	Type.Characteristic, 0x2BAA, "Track Segments Object Type"),
        UUID16(	Type.Characteristic, 0x2BAB, "Track Object Type"),
        UUID16(	Type.Characteristic, 0x2BAC, "Group Object Type"),
        UUID16(	Type.Characteristic, 0x2BAD, "Constant Tone Extension Enable"),
        UUID16(	Type.Characteristic, 0x2BAE, "Advertising Constant Tone Extension Minimum Length"),
        UUID16(	Type.Characteristic, 0x2BAF, "Advertising Constant Tone Extension Minimum Transmit Count"),
        UUID16(	Type.Characteristic, 0x2BB0, "Advertising Constant Tone Extension Transmit Duration"),
        UUID16(	Type.Characteristic, 0x2BB1, "Advertising Constant Tone Extension Interval"),
        UUID16(	Type.Characteristic, 0x2BB2, "Advertising Constant Tone Extension PHY"),
        UUID16(	Type.Characteristic, 0x2BB3, "Bearer Provider Name"),
        UUID16(	Type.Characteristic, 0x2BB4, "Bearer UCI"),
        UUID16(	Type.Characteristic, 0x2BB5, "Bearer Technology"),
        UUID16(	Type.Characteristic, 0x2BB6, "Bearer URI Schemes Supported List"),
        UUID16(	Type.Characteristic, 0x2BB7, "Bearer Signal Strength"),
        UUID16(	Type.Characteristic, 0x2BB8, "Bearer Signal Strength Reporting Interval"),
        UUID16(	Type.Characteristic, 0x2BB9, "Bearer List Current Calls"),
        UUID16(	Type.Characteristic, 0x2BBA, "Content Control ID"),
        UUID16(	Type.Characteristic, 0x2BBB, "Status Flags"),
        UUID16(	Type.Characteristic, 0x2BBC, "Incoming Call Target Bearer URI"),
        UUID16(	Type.Characteristic, 0x2BBD, "Call State"),
        UUID16(	Type.Characteristic, 0x2BBE, "Call Control Point"),
        UUID16(	Type.Characteristic, 0x2BBF, "Call Control Point Optional Opcodes"),
        UUID16(	Type.Characteristic, 0x2BC0, "Termination Reason"),
        UUID16(	Type.Characteristic, 0x2BC1, "Incoming Call"),
        UUID16(	Type.Characteristic, 0x2BC2, "Call Friendly Name"),
        UUID16(	Type.Characteristic, 0x2BC3, "Mute"),
        UUID16(	Type.Characteristic, 0x2BC4, "Sink ASE"),
        UUID16(	Type.Characteristic, 0x2BC5, "Source ASE"),
        UUID16(	Type.Characteristic, 0x2BC6, "ASE Control Point"),
        UUID16(	Type.Characteristic, 0x2BC7, "Broadcast Audio Scan Control Point"),
        UUID16(	Type.Characteristic, 0x2BC8, "Broadcast Receive State"),
        UUID16(	Type.Characteristic, 0x2BC9, "Sink PAC"),
        UUID16(	Type.Characteristic, 0x2BCA, "Sink Audio Locations"),
        UUID16(	Type.Characteristic, 0x2BCB, "Source PAC"),
        UUID16(	Type.Characteristic, 0x2BCC, "Source Audio Locations"),
        UUID16(	Type.Characteristic, 0x2BCD, "Available Audio Contexts"),
        UUID16(	Type.Characteristic, 0x2BCE, "Supported Audio Contexts"),
        UUID16(	Type.Characteristic, 0x2BCF, "Ammonia Concentration"),
        UUID16(	Type.Characteristic, 0x2BD0, "Carbon Monoxide Concentration"),
        UUID16(	Type.Characteristic, 0x2BD1, "Methane Concentration"),
        UUID16(	Type.Characteristic, 0x2BD2, "Nitrogen Dioxide Concentration"),
        UUID16(	Type.Characteristic, 0x2BD3, "Non-Methane Volatile Organic Compounds Concentration"),
        UUID16(	Type.Characteristic, 0x2BD4, "Ozone Concentration"),
        UUID16(	Type.Characteristic, 0x2BD5, "Particulate Matter - PM1 Concentration"),
        UUID16(	Type.Characteristic, 0x2BD6, "Particulate Matter - PM2.5 Concentration"),
        UUID16(	Type.Characteristic, 0x2BD7, "Particulate Matter - PM10 Concentration"),
        UUID16(	Type.Characteristic, 0x2BD8, "Sulfur Dioxide Concentration"),
        UUID16(	Type.Characteristic, 0x2BD9, "Sulfur Hexafluoride Concentration"),
        UUID16(	Type.Declaration, 0x2800, "Primary Service"),
        UUID16(	Type.Declaration, 0x2801, "Secondary Service"),
        UUID16(	Type.Declaration, 0x2802, "Include"),
        UUID16(	Type.Declaration, 0x2803, "Characteristic"),
        UUID16(	Type.Descriptor, 0x2900, "Characteristic Extended Properties"),
        UUID16(	Type.Descriptor, 0x2901, "Characteristic User Description"),
        UUID16(	Type.Descriptor, 0x2902, "Client Characteristic Configuration"),
        UUID16(	Type.Descriptor, 0x2903, "Server Characteristic Configuration"),
        UUID16(	Type.Descriptor, 0x2904, "Characteristic Presentation Format"),
        UUID16(	Type.Descriptor, 0x2905, "Characteristic Aggregate Format"),
        UUID16(	Type.Descriptor, 0x2906, "Valid Range"),
        UUID16(	Type.Descriptor, 0x2907, "External Report Reference"),
        UUID16(	Type.Descriptor, 0x2908, "Report Reference"),
        UUID16(	Type.Descriptor, 0x2909, "Number of Digitals"),
        UUID16(	Type.Descriptor, 0x290A, "Value Trigger Setting"),
        UUID16(	Type.Descriptor, 0x290B, "Environmental Sensing Configuration"),
        UUID16(	Type.Descriptor, 0x290C, "Environmental Sensing Measurement"),
        UUID16(	Type.Descriptor, 0x290D, "Environmental Sensing Trigger Setting"),
        UUID16(	Type.Descriptor, 0x290E, "Time Trigger Setting"),
        UUID16(	Type.Descriptor, 0x290F, "Complete BR-EDR Transport Block Data"),
        UUID16(	Type.Service, 0x1800, "Generic Access"),
        UUID16(	Type.Service, 0x1801, "Generic Attribute"),
        UUID16(	Type.Service, 0x1802, "Immediate Alert"),
        UUID16(	Type.Service, 0x1803, "Link Loss"),
        UUID16(	Type.Service, 0x1804, "Tx Power"),
        UUID16(	Type.Service, 0x1805, "Current Time"),
        UUID16(	Type.Service, 0x1806, "Reference Time Update"),
        UUID16(	Type.Service, 0x1807, "Next DST Change"),
        UUID16(	Type.Service, 0x1808, "Glucose"),
        UUID16(	Type.Service, 0x1809, "Health Thermometer"),
        UUID16(	Type.Service, 0x180A, "Device Information"),
        UUID16(	Type.Service, 0x180D, "Heart Rate"),
        UUID16(	Type.Service, 0x180E, "Phone Alert Status"),
        UUID16(	Type.Service, 0x180F, "Battery"),
        UUID16(	Type.Service, 0x1810, "Blood Pressure"),
        UUID16(	Type.Service, 0x1811, "Alert Notification"),
        UUID16(	Type.Service, 0x1812, "Human Interface Device"),
        UUID16(	Type.Service, 0x1813, "Scan Parameters"),
        UUID16(	Type.Service, 0x1814, "Running Speed and Cadence"),
        UUID16(	Type.Service, 0x1815, "Automation IO"),
        UUID16(	Type.Service, 0x1816, "Cycling Speed and Cadence"),
        UUID16(	Type.Service, 0x1818, "Cycling Power"),
        UUID16(	Type.Service, 0x1819, "Location and Navigation"),
        UUID16(	Type.Service, 0x181A, "Environmental Sensing"),
        UUID16(	Type.Service, 0x181B, "Body Composition"),
        UUID16(	Type.Service, 0x181C, "User Data"),
        UUID16(	Type.Service, 0x181D, "Weight Scale"),
        UUID16(	Type.Service, 0x181E, "Bond Management"),
        UUID16(	Type.Service, 0x181F, "Continuous Glucose Monitoring"),
        UUID16(	Type.Service, 0x1820, "Internet Protocol Support"),
        UUID16(	Type.Service, 0x1821, "Indoor Positioning"),
        UUID16(	Type.Service, 0x1822, "Pulse Oximeter"),
        UUID16(	Type.Service, 0x1823, "HTTP Proxy"),
        UUID16(	Type.Service, 0x1824, "Transport Discovery"),
        UUID16(	Type.Service, 0x1825, "Object Transfer"),
        UUID16(	Type.Service, 0x1826, "Fitness Machine"),
        UUID16(	Type.Service, 0x1827, "Mesh Provisioning"),
        UUID16(	Type.Service, 0x1828, "Mesh Proxy"),
        UUID16(	Type.Service, 0x1829, "Reconnection Configuration"),
        UUID16(	Type.Service, 0x183A, "Insulin Delivery"),
        UUID16(	Type.Service, 0x183B, "Binary Sensor"),
        UUID16(	Type.Service, 0x183C, "Emergency Configuration"),
        UUID16(	Type.Service, 0x183E, "Physical Activity Monitor"),
        UUID16(	Type.Service, 0x1843, "Audio Input Control"),
        UUID16(	Type.Service, 0x1844, "Volume Control"),
        UUID16(	Type.Service, 0x1845, "Volume Offset Control"),
        UUID16(	Type.Service, 0x1846, "Coordinated Set Identification Service"),
        UUID16(	Type.Service, 0x1847, "Device Time"),
        UUID16(	Type.Service, 0x1848, "Media Control Service"),
        UUID16(	Type.Service, 0x1849, "Generic Media Control Service"),
        UUID16(	Type.Service, 0x184A, "Constant Tone Extension"),
        UUID16(	Type.Service, 0x184B, "Telephone Bearer Service"),
        UUID16(	Type.Service, 0x184C, "Generic Telephone Bearer Service"),
        UUID16(	Type.Service, 0x184D, "Microphone Control"),
        UUID16(	Type.Service, 0x184E, "Audio Stream Control Service"),
        UUID16(	Type.Service, 0x184F, "Broadcast Audio Scan Service"),
        UUID16(	Type.Service, 0x1850, "Published Audio Capabilities Service"),
        UUID16(	Type.Service, 0x1851, "Basic Audio Announcement Service"),
        UUID16(	Type.Service, 0x1852, "Broadcast Audio Announcement Service"),
        UUID16(	Type.Unit, 0x2700, "unitless"),
        UUID16(	Type.Unit, 0x2701, "length (metre)"),
        UUID16(	Type.Unit, 0x2702, "mass (kilogram)"),
        UUID16(	Type.Unit, 0x2703, "time (second)"),
        UUID16(	Type.Unit, 0x2704, "electric current (ampere)"),
        UUID16(	Type.Unit, 0x2705, "thermodynamic temperature (kelvin)"),
        UUID16(	Type.Unit, 0x2706, "amount of substance (mole)"),
        UUID16(	Type.Unit, 0x2707, "luminous intensity (candela)"),
        UUID16(	Type.Unit, 0x2710, "area (square metres)"),
        UUID16(	Type.Unit, 0x2711, "volume (cubic metres)"),
        UUID16(	Type.Unit, 0x2712, "velocity (metres per second)"),
        UUID16(	Type.Unit, 0x2713, "acceleration (metres per second squared)"),
        UUID16(	Type.Unit, 0x2714, "wavenumber (reciprocal metre)"),
        UUID16(	Type.Unit, 0x2715, "density (kilogram per cubic metre)"),
        UUID16(	Type.Unit, 0x2716, "surface density (kilogram per square metre)"),
        UUID16(	Type.Unit, 0x2717, "specific volume (cubic metre per kilogram)"),
        UUID16(	Type.Unit, 0x2718, "current density (ampere per square metre)"),
        UUID16(	Type.Unit, 0x2719, "magnetic field strength (ampere per metre)"),
        UUID16(	Type.Unit, 0x271A, "amount concentration (mole per cubic metre)"),
        UUID16(	Type.Unit, 0x271B, "mass concentration (kilogram per cubic metre)"),
        UUID16(	Type.Unit, 0x271C, "luminance (candela per square metre)"),
        UUID16(	Type.Unit, 0x271D, "refractive index"),
        UUID16(	Type.Unit, 0x271E, "relative permeability"),
        UUID16(	Type.Unit, 0x2720, "plane angle (radian)"),
        UUID16(	Type.Unit, 0x2721, "solid angle (steradian)"),
        UUID16(	Type.Unit, 0x2722, "frequency (hertz)"),
        UUID16(	Type.Unit, 0x2723, "force (newton)"),
        UUID16(	Type.Unit, 0x2724, "pressure (pascal)"),
        UUID16(	Type.Unit, 0x2725, "energy (joule)"),
        UUID16(	Type.Unit, 0x2726, "power (watt)"),
        UUID16(	Type.Unit, 0x2727, "electric charge (coulomb)"),
        UUID16(	Type.Unit, 0x2728, "electric potential difference (volt)"),
        UUID16(	Type.Unit, 0x2729, "capacitance (farad)"),
        UUID16(	Type.Unit, 0x272A, "electric resistance (ohm)"),
        UUID16(	Type.Unit, 0x272B, "electric conductance (siemens)"),
        UUID16(	Type.Unit, 0x272C, "magnetic flux (weber)"),
        UUID16(	Type.Unit, 0x272D, "magnetic flux density (tesla)"),
        UUID16(	Type.Unit, 0x272E, "inductance (henry)"),
        UUID16(	Type.Unit, 0x272F, "Celsius temperature (degree Celsius)"),
        UUID16(	Type.Unit, 0x2730, "luminous flux (lumen)"),
        UUID16(	Type.Unit, 0x2731, "illuminance (lux)"),
        UUID16(	Type.Unit, 0x2732, "activity referred to a radionuclide (becquerel)"),
        UUID16(	Type.Unit, 0x2733, "absorbed dose (gray)"),
        UUID16(	Type.Unit, 0x2734, "dose equivalent (sievert)"),
        UUID16(	Type.Unit, 0x2735, "catalytic activity (katal)"),
        UUID16(	Type.Unit, 0x2740, "dynamic viscosity (pascal second)"),
        UUID16(	Type.Unit, 0x2741, "moment of force (newton metre)"),
        UUID16(	Type.Unit, 0x2742, "surface tension (newton per metre)"),
        UUID16(	Type.Unit, 0x2743, "angular velocity (radian per second)"),
        UUID16(	Type.Unit, 0x2744, "angular acceleration (radian per second squared)"),
        UUID16(	Type.Unit, 0x2745, "heat flux density (watt per square metre)"),
        UUID16(	Type.Unit, 0x2746, "heat capacity (joule per kelvin)"),
        UUID16(	Type.Unit, 0x2747, "specific heat capacity (joule per kilogram kelvin)"),
        UUID16(	Type.Unit, 0x2748, "specific energy (joule per kilogram)"),
        UUID16(	Type.Unit, 0x2749, "thermal conductivity (watt per metre kelvin)"),
        UUID16(	Type.Unit, 0x274A, "energy density (joule per cubic metre)"),
        UUID16(	Type.Unit, 0x274B, "electric field strength (volt per metre)"),
        UUID16(	Type.Unit, 0x274C, "electric charge density (coulomb per cubic metre)"),
        UUID16(	Type.Unit, 0x274D, "surface charge density (coulomb per square metre)"),
        UUID16(	Type.Unit, 0x274E, "electric flux density (coulomb per square metre)"),
        UUID16(	Type.Unit, 0x274F, "permittivity (farad per metre)"),
        UUID16(	Type.Unit, 0x2750, "permeability (henry per metre)"),
        UUID16(	Type.Unit, 0x2751, "molar energy (joule per mole)"),
        UUID16(	Type.Unit, 0x2752, "molar entropy (joule per mole kelvin)"),
        UUID16(	Type.Unit, 0x2753, "exposure (coulomb per kilogram)"),
        UUID16(	Type.Unit, 0x2754, "absorbed dose rate (gray per second)"),
        UUID16(	Type.Unit, 0x2755, "radiant intensity (watt per steradian)"),
        UUID16(	Type.Unit, 0x2756, "radiance (watt per square metre steradian)"),
        UUID16(	Type.Unit, 0x2757, "catalytic activity concentration (katal per cubic metre)"),
        UUID16(	Type.Unit, 0x2760, "time (minute)"),
        UUID16(	Type.Unit, 0x2761, "time (hour)"),
        UUID16(	Type.Unit, 0x2762, "time (day)"),
        UUID16(	Type.Unit, 0x2763, "plane angle (degree)"),
        UUID16(	Type.Unit, 0x2764, "plane angle (minute)"),
        UUID16(	Type.Unit, 0x2765, "plane angle (second)"),
        UUID16(	Type.Unit, 0x2766, "area (hectare)"),
        UUID16(	Type.Unit, 0x2767, "volume (litre)"),
        UUID16(	Type.Unit, 0x2768, "mass (tonne)"),
        UUID16(	Type.Unit, 0x2780, "pressure (bar)"),
        UUID16(	Type.Unit, 0x2781, "pressure (millimetre of mercury)"),
        UUID16(	Type.Unit, 0x2782, "length (ångström)"),
        UUID16(	Type.Unit, 0x2783, "length (nautical mile)"),
        UUID16(	Type.Unit, 0x2784, "area (barn)"),
        UUID16(	Type.Unit, 0x2785, "velocity (knot)"),
        UUID16(	Type.Unit, 0x2786, "logarithmic radio quantity (neper)"),
        UUID16(	Type.Unit, 0x2787, "logarithmic radio quantity (bel)"),
        UUID16(	Type.Unit, 0x27A0, "length (yard)"),
        UUID16(	Type.Unit, 0x27A1, "length (parsec)"),
        UUID16(	Type.Unit, 0x27A2, "length (inch)"),
        UUID16(	Type.Unit, 0x27A3, "length (foot)"),
        UUID16(	Type.Unit, 0x27A4, "length (mile)"),
        UUID16(	Type.Unit, 0x27A5, "pressure (pound-force per square inch)"),
        UUID16(	Type.Unit, 0x27A6, "velocity (kilometre per hour)"),
        UUID16(	Type.Unit, 0x27A7, "velocity (mile per hour)"),
        UUID16(	Type.Unit, 0x27A8, "angular velocity (revolution per minute)"),
        UUID16(	Type.Unit, 0x27A9, "energy (gram calorie)"),
        UUID16(	Type.Unit, 0x27AA, "energy (kilogram calorie)"),
        UUID16(	Type.Unit, 0x27AB, "energy (kilowatt hour)"),
        UUID16(	Type.Unit, 0x27AC, "thermodynamic temperature (degree Fahrenheit)"),
        UUID16(	Type.Unit, 0x27AD, "percentage"),
        UUID16(	Type.Unit, 0x27AE, "per mille"),
        UUID16(	Type.Unit, 0x27AF, "period (beats per minute)"),
        UUID16(	Type.Unit, 0x27B0, "electric charge (ampere hours)"),
        UUID16(	Type.Unit, 0x27B1, "mass density (milligram per decilitre)"),
        UUID16(	Type.Unit, 0x27B2, "mass density (millimole per litre)"),
        UUID16(	Type.Unit, 0x27B3, "time (year)"),
        UUID16(	Type.Unit, 0x27B4, "time (month)"),
        UUID16(	Type.Unit, 0x27B5, "concentration (count per cubic metre)"),
        UUID16(	Type.Unit, 0x27B6, "irradiance (watt per square metre)"),
        UUID16(	Type.Unit, 0x27B7, "milliliter (per kilogram per minute)"),
        UUID16(	Type.Unit, 0x27B8, "mass (pound)"),
        UUID16(	Type.Unit, 0x27B9, "metabolic equivalent"),
        UUID16(	Type.Unit, 0x27BA, "step (per minute)"),
        UUID16(	Type.Unit, 0x27BC, "stroke (per minute)"),
        UUID16(	Type.Unit, 0x27BD, "pace (kilometre per minute)"),
        UUID16(	Type.Unit, 0x27BE, "luminous efficacy (lumen per watt)"),
        UUID16(	Type.Unit, 0x27BF, "luminous energy (lumen hour)"),
        UUID16(	Type.Unit, 0x27C0, "luminous exposure (lux hour)"),
        UUID16(	Type.Unit, 0x27C1, "mass flow (gram per second)"),
        UUID16(	Type.Unit, 0x27C2, "volume flow (litre per second)"),
        UUID16(	Type.Unit, 0x27C3, "sound pressure (decible)"),
        UUID16(	Type.Unit, 0x27C4, "parts per million"),
        UUID16(	Type.Unit, 0x27C5, "parts per billion"),
        UUID16(	Type.Protocol, 0x0001, "SDP"),
        UUID16(	Type.Protocol, 0x0002, "UDP"),
        UUID16(	Type.Protocol, 0x0003, "RFCOMM"),
        UUID16(	Type.Protocol, 0x0004, "TCP"),
        UUID16(	Type.Protocol, 0x0005, "TCS-BIN"),
        UUID16(	Type.Protocol, 0x0006, "TCS-AT"),
        UUID16(	Type.Protocol, 0x0007, "ATT"),
        UUID16(	Type.Protocol, 0x0008, "OBEX"),
        UUID16(	Type.Protocol, 0x0009, "IP"),
        UUID16(	Type.Protocol, 0x000A, "FTP"),
        UUID16(	Type.Protocol, 0x000C, "HTTP"),
        UUID16(	Type.Protocol, 0x000E, "WSP"),
        UUID16(	Type.Protocol, 0x000F, "BNEP"),
        UUID16(	Type.Protocol, 0x0010, "UPNP"),
        UUID16(	Type.Protocol, 0x0011, "HIDP"),
        UUID16(	Type.Protocol, 0x0012, "HardcopyControlChannel"),
        UUID16(	Type.Protocol, 0x0014, "HardcopyDataChannel"),
        UUID16(	Type.Protocol, 0x0016, "HardcopyNotification"),
        UUID16(	Type.Protocol, 0x0017, "AVCTP"),
        UUID16(	Type.Protocol, 0x0019, "AVDTP"),
        UUID16(	Type.Protocol, 0x001B, "CMTP"),
        UUID16(	Type.Protocol, 0x001E, "MCAPControlChannel"),
        UUID16(	Type.Protocol, 0x001F, "MCAPDataChannel"),
        UUID16(	Type.Protocol, 0x0100, "L2CAP"),
        UUID16(	Type.SDOGattService, 0xFFF3, "FiRa Consortium"),
        UUID16(	Type.SDOGattService, 0xFFF4, "FiRa Consortium"),
        UUID16(	Type.SDOGattService, 0xFFF5, "Car Connectivity Consortium, LLC"),
        UUID16(	Type.SDOGattService, 0xFFF6, "ZigBee Alliance"),
        UUID16(	Type.SDOGattService, 0xFFF7, "ZigBee Alliance"),
        UUID16(	Type.SDOGattService, 0xFFF8, "Mopria Alliance"),
        UUID16(	Type.SDOGattService, 0xFFF9, "Fast IDentity Online Alliance (FIDO)"),
        UUID16(	Type.SDOGattService, 0xFFFA, "ASTM International"),
        UUID16(	Type.SDOGattService, 0xFFFB, "Thread Group, Inc."),
        UUID16(	Type.SDOGattService, 0xFFFC, "AirFuel Alliance"),
        UUID16(	Type.SDOGattService, 0xFFFD, "Fast IDentity Online Alliance (FIDO)"),
        UUID16(	Type.SDOGattService, 0xFFFE, "AirFuel Alliance (formerly Alliance for Wireless Power)"),
        UUID16(	Type.ClassAndProfile, 0x1000, "ServiceDiscoveryServerServiceClassID"),
        UUID16(	Type.ClassAndProfile, 0x1001, "BrowseGroupDescriptorServiceClassID"),
        UUID16(	Type.ClassAndProfile, 0x1101, "SerialPort"),
        UUID16(	Type.ClassAndProfile, 0x1102, "LANAccessUsingPPP"),
        UUID16(	Type.ClassAndProfile, 0x1103, "DialupNetworking"),
        UUID16(	Type.ClassAndProfile, 0x1104, "IrMCSync"),
        UUID16(	Type.ClassAndProfile, 0x1105, "OBEXObjectPush"),
        UUID16(	Type.ClassAndProfile, 0x1106, "OBEXFileTransfer"),
        UUID16(	Type.ClassAndProfile, 0x1107, "IrMCSyncCommand"),
        UUID16(	Type.ClassAndProfile, 0x1108, "Headset"),
        UUID16(	Type.ClassAndProfile, 0x1109, "CordlessTelephony"),
        UUID16(	Type.ClassAndProfile, 0x110A, "AudioSource"),
        UUID16(	Type.ClassAndProfile, 0x110B, "AudioSink"),
        UUID16(	Type.ClassAndProfile, 0x110C, "A/V_RemoteControlTarget"),
        UUID16(	Type.ClassAndProfile, 0x110D, "AdvancedAudioDistribution"),
        UUID16(	Type.ClassAndProfile, 0x110E, "A/V_RemoteControl"),
        UUID16(	Type.ClassAndProfile, 0x110F, "A/V_RemoteControlController"),
        UUID16(	Type.ClassAndProfile, 0x1110, "Intercom"),
        UUID16(	Type.ClassAndProfile, 0x1111, "Fax"),
        UUID16(	Type.ClassAndProfile, 0x1112, "Headset - Audio Gateway"),
        UUID16(	Type.ClassAndProfile, 0x1113, "WAP"),
        UUID16(	Type.ClassAndProfile, 0x1114, "WAP_CLIENT"),
        UUID16(	Type.ClassAndProfile, 0x1115, "PANU"),
        UUID16(	Type.ClassAndProfile, 0x1116, "NAP"),
        UUID16(	Type.ClassAndProfile, 0x1117, "GN"),
        UUID16(	Type.ClassAndProfile, 0x1118, "DirectPrinting"),
        UUID16(	Type.ClassAndProfile, 0x1119, "ReferencePrinting"),
        UUID16(	Type.ClassAndProfile, 0x111A, "Basic Imaging Profile"),
        UUID16(	Type.ClassAndProfile, 0x111B, "ImagingResponder"),
        UUID16(	Type.ClassAndProfile, 0x111C, "ImagingAutomaticArchive"),
        UUID16(	Type.ClassAndProfile, 0x111D, "ImagingReferencedObjects"),
        UUID16(	Type.ClassAndProfile, 0x111E, "Handsfree"),
        UUID16(	Type.ClassAndProfile, 0x111F, "HandsfreeAudioGateway"),
        UUID16(	Type.ClassAndProfile, 0x1120, "DirectPrintingReferenceObjectsService"),
        UUID16(	Type.ClassAndProfile, 0x1121, "ReflectedUI"),
        UUID16(	Type.ClassAndProfile, 0x1122, "BasicPrinting"),
        UUID16(	Type.ClassAndProfile, 0x1123, "PrintingStatus"),
        UUID16(	Type.ClassAndProfile, 0x1124, "HumanInterfaceDeviceService"),
        UUID16(	Type.ClassAndProfile, 0x1125, "HardcopyCableReplacement"),
        UUID16(	Type.ClassAndProfile, 0x1126, "HCR_Print"),
        UUID16(	Type.ClassAndProfile, 0x1127, "HCR_Scan"),
        UUID16(	Type.ClassAndProfile, 0x1128, "Common_ISDN_Access"),
        UUID16(	Type.ClassAndProfile, 0x112D, "SIM_Access"),
        UUID16(	Type.ClassAndProfile, 0x112E, "Phonebook Access - PCE"),
        UUID16(	Type.ClassAndProfile, 0x112F, "Phonebook Access - PSE"),
        UUID16(	Type.ClassAndProfile, 0x1130, "Phonebook Access"),
        UUID16(	Type.ClassAndProfile, 0x1131, "Headset - HS"),
        UUID16(	Type.ClassAndProfile, 0x1132, "Message Access Server"),
        UUID16(	Type.ClassAndProfile, 0x1133, "Message Notification Server"),
        UUID16(	Type.ClassAndProfile, 0x1134, "Message Access Profile"),
        UUID16(	Type.ClassAndProfile, 0x1135, "GNSS"),
        UUID16(	Type.ClassAndProfile, 0x1136, "GNSS_Server"),
        UUID16(	Type.ClassAndProfile, 0x1137, "3D Display"),
        UUID16(	Type.ClassAndProfile, 0x1138, "3D Glasses"),
        UUID16(	Type.ClassAndProfile, 0x1139, "3D Synchronization"),
        UUID16(	Type.ClassAndProfile, 0x113A, "MPS Profile UUID"),
        UUID16(	Type.ClassAndProfile, 0x113B, "MPS SC UUID"),
        UUID16(	Type.ClassAndProfile, 0x113C, "CTN Access Service"),
        UUID16(	Type.ClassAndProfile, 0x113D, "CTN Notification Service"),
        UUID16(	Type.ClassAndProfile, 0x113E, "CTN Profile"),
        UUID16(	Type.ClassAndProfile, 0x1200, "PnPInformation"),
        UUID16(	Type.ClassAndProfile, 0x1201, "GenericNetworking"),
        UUID16(	Type.ClassAndProfile, 0x1202, "GenericFileTransfer"),
        UUID16(	Type.ClassAndProfile, 0x1203, "GenericAudio"),
        UUID16(	Type.ClassAndProfile, 0x1204, "GenericTelephony"),
        UUID16(	Type.ClassAndProfile, 0x1205, "UPNP_Service"),
        UUID16(	Type.ClassAndProfile, 0x1206, "UPNP_IP_Service"),
        UUID16(	Type.ClassAndProfile, 0x1300, "ESDP_UPNP_IP_PAN"),
        UUID16(	Type.ClassAndProfile, 0x1301, "ESDP_UPNP_IP_LAP"),
        UUID16(	Type.ClassAndProfile, 0x1302, "ESDP_UPNP_L2CAP"),
        UUID16(	Type.ClassAndProfile, 0x1303, "VideoSource"),
        UUID16(	Type.ClassAndProfile, 0x1304, "VideoSink"),
        UUID16(	Type.ClassAndProfile, 0x1305, "VideoDistribution"),
        UUID16(	Type.ClassAndProfile, 0x1400, "HDP"),
        UUID16(	Type.ClassAndProfile, 0x1401, "HDP Source"),
        UUID16(	Type.ClassAndProfile, 0x1402, "HDP Sink"),
    )
}